// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file imu_topic_base.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__IMU_TOPIC_BASE_IMU_TOPIC_BASE_HPP
#define FAST_DDS_GENERATED__IMU_TOPIC_BASE_IMU_TOPIC_BASE_HPP

#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMU_TOPIC_BASE_SOURCE)
#define IMU_TOPIC_BASE_DllAPI __declspec( dllexport )
#else
#define IMU_TOPIC_BASE_DllAPI __declspec( dllimport )
#endif // IMU_TOPIC_BASE_SOURCE
#else
#define IMU_TOPIC_BASE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMU_TOPIC_BASE_DllAPI
#endif // _WIN32

namespace imu_topic_base {

/*!
 * @brief This class represents the structure IMUData defined by the user in the IDL file.
 * @ingroup imu_topic_base
 */
class IMUData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport IMUData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~IMUData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object IMUData that will be copied.
     */
    eProsima_user_DllExport IMUData(
            const IMUData& x)
    {
                    m_orientation_w = x.m_orientation_w;

                    m_orientation_x = x.m_orientation_x;

                    m_orientation_y = x.m_orientation_y;

                    m_orientation_z = x.m_orientation_z;

                    m_angular_velocity_x = x.m_angular_velocity_x;

                    m_angular_velocity_y = x.m_angular_velocity_y;

                    m_angular_velocity_z = x.m_angular_velocity_z;

                    m_linear_acceleration_x = x.m_linear_acceleration_x;

                    m_linear_acceleration_y = x.m_linear_acceleration_y;

                    m_linear_acceleration_z = x.m_linear_acceleration_z;

                    m_roll = x.m_roll;

                    m_pitch = x.m_pitch;

                    m_yaw = x.m_yaw;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object IMUData that will be copied.
     */
    eProsima_user_DllExport IMUData(
            IMUData&& x) noexcept
    {
        m_orientation_w = x.m_orientation_w;
        m_orientation_x = x.m_orientation_x;
        m_orientation_y = x.m_orientation_y;
        m_orientation_z = x.m_orientation_z;
        m_angular_velocity_x = x.m_angular_velocity_x;
        m_angular_velocity_y = x.m_angular_velocity_y;
        m_angular_velocity_z = x.m_angular_velocity_z;
        m_linear_acceleration_x = x.m_linear_acceleration_x;
        m_linear_acceleration_y = x.m_linear_acceleration_y;
        m_linear_acceleration_z = x.m_linear_acceleration_z;
        m_roll = x.m_roll;
        m_pitch = x.m_pitch;
        m_yaw = x.m_yaw;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object IMUData that will be copied.
     */
    eProsima_user_DllExport IMUData& operator =(
            const IMUData& x)
    {

                    m_orientation_w = x.m_orientation_w;

                    m_orientation_x = x.m_orientation_x;

                    m_orientation_y = x.m_orientation_y;

                    m_orientation_z = x.m_orientation_z;

                    m_angular_velocity_x = x.m_angular_velocity_x;

                    m_angular_velocity_y = x.m_angular_velocity_y;

                    m_angular_velocity_z = x.m_angular_velocity_z;

                    m_linear_acceleration_x = x.m_linear_acceleration_x;

                    m_linear_acceleration_y = x.m_linear_acceleration_y;

                    m_linear_acceleration_z = x.m_linear_acceleration_z;

                    m_roll = x.m_roll;

                    m_pitch = x.m_pitch;

                    m_yaw = x.m_yaw;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object IMUData that will be copied.
     */
    eProsima_user_DllExport IMUData& operator =(
            IMUData&& x) noexcept
    {

        m_orientation_w = x.m_orientation_w;
        m_orientation_x = x.m_orientation_x;
        m_orientation_y = x.m_orientation_y;
        m_orientation_z = x.m_orientation_z;
        m_angular_velocity_x = x.m_angular_velocity_x;
        m_angular_velocity_y = x.m_angular_velocity_y;
        m_angular_velocity_z = x.m_angular_velocity_z;
        m_linear_acceleration_x = x.m_linear_acceleration_x;
        m_linear_acceleration_y = x.m_linear_acceleration_y;
        m_linear_acceleration_z = x.m_linear_acceleration_z;
        m_roll = x.m_roll;
        m_pitch = x.m_pitch;
        m_yaw = x.m_yaw;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x IMUData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const IMUData& x) const
    {
        return (m_orientation_w == x.m_orientation_w &&
           m_orientation_x == x.m_orientation_x &&
           m_orientation_y == x.m_orientation_y &&
           m_orientation_z == x.m_orientation_z &&
           m_angular_velocity_x == x.m_angular_velocity_x &&
           m_angular_velocity_y == x.m_angular_velocity_y &&
           m_angular_velocity_z == x.m_angular_velocity_z &&
           m_linear_acceleration_x == x.m_linear_acceleration_x &&
           m_linear_acceleration_y == x.m_linear_acceleration_y &&
           m_linear_acceleration_z == x.m_linear_acceleration_z &&
           m_roll == x.m_roll &&
           m_pitch == x.m_pitch &&
           m_yaw == x.m_yaw);
    }

    /*!
     * @brief Comparison operator.
     * @param x IMUData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const IMUData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member orientation_w
     * @param _orientation_w New value for member orientation_w
     */
    eProsima_user_DllExport void orientation_w(
            double _orientation_w)
    {
        m_orientation_w = _orientation_w;
    }

    /*!
     * @brief This function returns the value of member orientation_w
     * @return Value of member orientation_w
     */
    eProsima_user_DllExport double orientation_w() const
    {
        return m_orientation_w;
    }

    /*!
     * @brief This function returns a reference to member orientation_w
     * @return Reference to member orientation_w
     */
    eProsima_user_DllExport double& orientation_w()
    {
        return m_orientation_w;
    }


    /*!
     * @brief This function sets a value in member orientation_x
     * @param _orientation_x New value for member orientation_x
     */
    eProsima_user_DllExport void orientation_x(
            double _orientation_x)
    {
        m_orientation_x = _orientation_x;
    }

    /*!
     * @brief This function returns the value of member orientation_x
     * @return Value of member orientation_x
     */
    eProsima_user_DllExport double orientation_x() const
    {
        return m_orientation_x;
    }

    /*!
     * @brief This function returns a reference to member orientation_x
     * @return Reference to member orientation_x
     */
    eProsima_user_DllExport double& orientation_x()
    {
        return m_orientation_x;
    }


    /*!
     * @brief This function sets a value in member orientation_y
     * @param _orientation_y New value for member orientation_y
     */
    eProsima_user_DllExport void orientation_y(
            double _orientation_y)
    {
        m_orientation_y = _orientation_y;
    }

    /*!
     * @brief This function returns the value of member orientation_y
     * @return Value of member orientation_y
     */
    eProsima_user_DllExport double orientation_y() const
    {
        return m_orientation_y;
    }

    /*!
     * @brief This function returns a reference to member orientation_y
     * @return Reference to member orientation_y
     */
    eProsima_user_DllExport double& orientation_y()
    {
        return m_orientation_y;
    }


    /*!
     * @brief This function sets a value in member orientation_z
     * @param _orientation_z New value for member orientation_z
     */
    eProsima_user_DllExport void orientation_z(
            double _orientation_z)
    {
        m_orientation_z = _orientation_z;
    }

    /*!
     * @brief This function returns the value of member orientation_z
     * @return Value of member orientation_z
     */
    eProsima_user_DllExport double orientation_z() const
    {
        return m_orientation_z;
    }

    /*!
     * @brief This function returns a reference to member orientation_z
     * @return Reference to member orientation_z
     */
    eProsima_user_DllExport double& orientation_z()
    {
        return m_orientation_z;
    }


    /*!
     * @brief This function sets a value in member angular_velocity_x
     * @param _angular_velocity_x New value for member angular_velocity_x
     */
    eProsima_user_DllExport void angular_velocity_x(
            double _angular_velocity_x)
    {
        m_angular_velocity_x = _angular_velocity_x;
    }

    /*!
     * @brief This function returns the value of member angular_velocity_x
     * @return Value of member angular_velocity_x
     */
    eProsima_user_DllExport double angular_velocity_x() const
    {
        return m_angular_velocity_x;
    }

    /*!
     * @brief This function returns a reference to member angular_velocity_x
     * @return Reference to member angular_velocity_x
     */
    eProsima_user_DllExport double& angular_velocity_x()
    {
        return m_angular_velocity_x;
    }


    /*!
     * @brief This function sets a value in member angular_velocity_y
     * @param _angular_velocity_y New value for member angular_velocity_y
     */
    eProsima_user_DllExport void angular_velocity_y(
            double _angular_velocity_y)
    {
        m_angular_velocity_y = _angular_velocity_y;
    }

    /*!
     * @brief This function returns the value of member angular_velocity_y
     * @return Value of member angular_velocity_y
     */
    eProsima_user_DllExport double angular_velocity_y() const
    {
        return m_angular_velocity_y;
    }

    /*!
     * @brief This function returns a reference to member angular_velocity_y
     * @return Reference to member angular_velocity_y
     */
    eProsima_user_DllExport double& angular_velocity_y()
    {
        return m_angular_velocity_y;
    }


    /*!
     * @brief This function sets a value in member angular_velocity_z
     * @param _angular_velocity_z New value for member angular_velocity_z
     */
    eProsima_user_DllExport void angular_velocity_z(
            double _angular_velocity_z)
    {
        m_angular_velocity_z = _angular_velocity_z;
    }

    /*!
     * @brief This function returns the value of member angular_velocity_z
     * @return Value of member angular_velocity_z
     */
    eProsima_user_DllExport double angular_velocity_z() const
    {
        return m_angular_velocity_z;
    }

    /*!
     * @brief This function returns a reference to member angular_velocity_z
     * @return Reference to member angular_velocity_z
     */
    eProsima_user_DllExport double& angular_velocity_z()
    {
        return m_angular_velocity_z;
    }


    /*!
     * @brief This function sets a value in member linear_acceleration_x
     * @param _linear_acceleration_x New value for member linear_acceleration_x
     */
    eProsima_user_DllExport void linear_acceleration_x(
            double _linear_acceleration_x)
    {
        m_linear_acceleration_x = _linear_acceleration_x;
    }

    /*!
     * @brief This function returns the value of member linear_acceleration_x
     * @return Value of member linear_acceleration_x
     */
    eProsima_user_DllExport double linear_acceleration_x() const
    {
        return m_linear_acceleration_x;
    }

    /*!
     * @brief This function returns a reference to member linear_acceleration_x
     * @return Reference to member linear_acceleration_x
     */
    eProsima_user_DllExport double& linear_acceleration_x()
    {
        return m_linear_acceleration_x;
    }


    /*!
     * @brief This function sets a value in member linear_acceleration_y
     * @param _linear_acceleration_y New value for member linear_acceleration_y
     */
    eProsima_user_DllExport void linear_acceleration_y(
            double _linear_acceleration_y)
    {
        m_linear_acceleration_y = _linear_acceleration_y;
    }

    /*!
     * @brief This function returns the value of member linear_acceleration_y
     * @return Value of member linear_acceleration_y
     */
    eProsima_user_DllExport double linear_acceleration_y() const
    {
        return m_linear_acceleration_y;
    }

    /*!
     * @brief This function returns a reference to member linear_acceleration_y
     * @return Reference to member linear_acceleration_y
     */
    eProsima_user_DllExport double& linear_acceleration_y()
    {
        return m_linear_acceleration_y;
    }


    /*!
     * @brief This function sets a value in member linear_acceleration_z
     * @param _linear_acceleration_z New value for member linear_acceleration_z
     */
    eProsima_user_DllExport void linear_acceleration_z(
            double _linear_acceleration_z)
    {
        m_linear_acceleration_z = _linear_acceleration_z;
    }

    /*!
     * @brief This function returns the value of member linear_acceleration_z
     * @return Value of member linear_acceleration_z
     */
    eProsima_user_DllExport double linear_acceleration_z() const
    {
        return m_linear_acceleration_z;
    }

    /*!
     * @brief This function returns a reference to member linear_acceleration_z
     * @return Reference to member linear_acceleration_z
     */
    eProsima_user_DllExport double& linear_acceleration_z()
    {
        return m_linear_acceleration_z;
    }


    /*!
     * @brief This function sets a value in member roll
     * @param _roll New value for member roll
     */
    eProsima_user_DllExport void roll(
            double _roll)
    {
        m_roll = _roll;
    }

    /*!
     * @brief This function returns the value of member roll
     * @return Value of member roll
     */
    eProsima_user_DllExport double roll() const
    {
        return m_roll;
    }

    /*!
     * @brief This function returns a reference to member roll
     * @return Reference to member roll
     */
    eProsima_user_DllExport double& roll()
    {
        return m_roll;
    }


    /*!
     * @brief This function sets a value in member pitch
     * @param _pitch New value for member pitch
     */
    eProsima_user_DllExport void pitch(
            double _pitch)
    {
        m_pitch = _pitch;
    }

    /*!
     * @brief This function returns the value of member pitch
     * @return Value of member pitch
     */
    eProsima_user_DllExport double pitch() const
    {
        return m_pitch;
    }

    /*!
     * @brief This function returns a reference to member pitch
     * @return Reference to member pitch
     */
    eProsima_user_DllExport double& pitch()
    {
        return m_pitch;
    }


    /*!
     * @brief This function sets a value in member yaw
     * @param _yaw New value for member yaw
     */
    eProsima_user_DllExport void yaw(
            double _yaw)
    {
        m_yaw = _yaw;
    }

    /*!
     * @brief This function returns the value of member yaw
     * @return Value of member yaw
     */
    eProsima_user_DllExport double yaw() const
    {
        return m_yaw;
    }

    /*!
     * @brief This function returns a reference to member yaw
     * @return Reference to member yaw
     */
    eProsima_user_DllExport double& yaw()
    {
        return m_yaw;
    }



private:

    double m_orientation_w{0.0};
    double m_orientation_x{0.0};
    double m_orientation_y{0.0};
    double m_orientation_z{0.0};
    double m_angular_velocity_x{0.0};
    double m_angular_velocity_y{0.0};
    double m_angular_velocity_z{0.0};
    double m_linear_acceleration_x{0.0};
    double m_linear_acceleration_y{0.0};
    double m_linear_acceleration_z{0.0};
    double m_roll{0.0};
    double m_pitch{0.0};
    double m_yaw{0.0};

};

} // namespace imu_topic_base

#endif // _FAST_DDS_GENERATED_IMU_TOPIC_BASE_IMU_TOPIC_BASE_HPP_


