// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file imu_topic_baseTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "imu_topic_baseTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "imu_topic_base.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace imu_topic_base {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_IMUData_type_identifier(
        TypeIdentifierPair& type_ids_IMUData)
{

    ReturnCode_t return_code_IMUData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_IMUData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "imu_topic_base::IMUData", type_ids_IMUData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_IMUData)
    {
        StructTypeFlag struct_flags_IMUData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_IMUData = "imu_topic_base::IMUData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_IMUData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_IMUData;
        AppliedAnnotationSeq tmp_ann_custom_IMUData;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_IMUData;
        if (!tmp_ann_custom_IMUData.empty())
        {
            ann_custom_IMUData = tmp_ann_custom_IMUData;
        }

        CompleteTypeDetail detail_IMUData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_IMUData, ann_custom_IMUData, type_name_IMUData.to_string());
        CompleteStructHeader header_IMUData;
        header_IMUData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_IMUData);
        CompleteStructMemberSeq member_seq_IMUData;
        {
            TypeIdentifierPair type_ids_orientation_w;
            ReturnCode_t return_code_orientation_w {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_w =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_w);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_w)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_w Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_w = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_w = 0x00000000;
            bool common_orientation_w_ec {false};
            CommonStructMember common_orientation_w {TypeObjectUtils::build_common_struct_member(member_id_orientation_w, member_flags_orientation_w, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_w, common_orientation_w_ec))};
            if (!common_orientation_w_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_w member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_w = "orientation_w";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_w;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_orientation_w = TypeObjectUtils::build_complete_member_detail(name_orientation_w, member_ann_builtin_orientation_w, ann_custom_IMUData);
            CompleteStructMember member_orientation_w = TypeObjectUtils::build_complete_struct_member(common_orientation_w, detail_orientation_w);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_orientation_w);
        }
        {
            TypeIdentifierPair type_ids_orientation_x;
            ReturnCode_t return_code_orientation_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_x = 0x00000001;
            bool common_orientation_x_ec {false};
            CommonStructMember common_orientation_x {TypeObjectUtils::build_common_struct_member(member_id_orientation_x, member_flags_orientation_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_x, common_orientation_x_ec))};
            if (!common_orientation_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_x = "orientation_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_x;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_orientation_x = TypeObjectUtils::build_complete_member_detail(name_orientation_x, member_ann_builtin_orientation_x, ann_custom_IMUData);
            CompleteStructMember member_orientation_x = TypeObjectUtils::build_complete_struct_member(common_orientation_x, detail_orientation_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_orientation_x);
        }
        {
            TypeIdentifierPair type_ids_orientation_y;
            ReturnCode_t return_code_orientation_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_y = 0x00000002;
            bool common_orientation_y_ec {false};
            CommonStructMember common_orientation_y {TypeObjectUtils::build_common_struct_member(member_id_orientation_y, member_flags_orientation_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_y, common_orientation_y_ec))};
            if (!common_orientation_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_y = "orientation_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_y;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_orientation_y = TypeObjectUtils::build_complete_member_detail(name_orientation_y, member_ann_builtin_orientation_y, ann_custom_IMUData);
            CompleteStructMember member_orientation_y = TypeObjectUtils::build_complete_struct_member(common_orientation_y, detail_orientation_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_orientation_y);
        }
        {
            TypeIdentifierPair type_ids_orientation_z;
            ReturnCode_t return_code_orientation_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_z = 0x00000003;
            bool common_orientation_z_ec {false};
            CommonStructMember common_orientation_z {TypeObjectUtils::build_common_struct_member(member_id_orientation_z, member_flags_orientation_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_z, common_orientation_z_ec))};
            if (!common_orientation_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_z = "orientation_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_z;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_orientation_z = TypeObjectUtils::build_complete_member_detail(name_orientation_z, member_ann_builtin_orientation_z, ann_custom_IMUData);
            CompleteStructMember member_orientation_z = TypeObjectUtils::build_complete_struct_member(common_orientation_z, detail_orientation_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_orientation_z);
        }
        {
            TypeIdentifierPair type_ids_angular_velocity_x;
            ReturnCode_t return_code_angular_velocity_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_angular_velocity_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_angular_velocity_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_angular_velocity_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "angular_velocity_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_angular_velocity_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_angular_velocity_x = 0x00000004;
            bool common_angular_velocity_x_ec {false};
            CommonStructMember common_angular_velocity_x {TypeObjectUtils::build_common_struct_member(member_id_angular_velocity_x, member_flags_angular_velocity_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_angular_velocity_x, common_angular_velocity_x_ec))};
            if (!common_angular_velocity_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure angular_velocity_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_angular_velocity_x = "angular_velocity_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_angular_velocity_x;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_angular_velocity_x = TypeObjectUtils::build_complete_member_detail(name_angular_velocity_x, member_ann_builtin_angular_velocity_x, ann_custom_IMUData);
            CompleteStructMember member_angular_velocity_x = TypeObjectUtils::build_complete_struct_member(common_angular_velocity_x, detail_angular_velocity_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_angular_velocity_x);
        }
        {
            TypeIdentifierPair type_ids_angular_velocity_y;
            ReturnCode_t return_code_angular_velocity_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_angular_velocity_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_angular_velocity_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_angular_velocity_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "angular_velocity_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_angular_velocity_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_angular_velocity_y = 0x00000005;
            bool common_angular_velocity_y_ec {false};
            CommonStructMember common_angular_velocity_y {TypeObjectUtils::build_common_struct_member(member_id_angular_velocity_y, member_flags_angular_velocity_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_angular_velocity_y, common_angular_velocity_y_ec))};
            if (!common_angular_velocity_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure angular_velocity_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_angular_velocity_y = "angular_velocity_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_angular_velocity_y;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_angular_velocity_y = TypeObjectUtils::build_complete_member_detail(name_angular_velocity_y, member_ann_builtin_angular_velocity_y, ann_custom_IMUData);
            CompleteStructMember member_angular_velocity_y = TypeObjectUtils::build_complete_struct_member(common_angular_velocity_y, detail_angular_velocity_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_angular_velocity_y);
        }
        {
            TypeIdentifierPair type_ids_angular_velocity_z;
            ReturnCode_t return_code_angular_velocity_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_angular_velocity_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_angular_velocity_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_angular_velocity_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "angular_velocity_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_angular_velocity_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_angular_velocity_z = 0x00000006;
            bool common_angular_velocity_z_ec {false};
            CommonStructMember common_angular_velocity_z {TypeObjectUtils::build_common_struct_member(member_id_angular_velocity_z, member_flags_angular_velocity_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_angular_velocity_z, common_angular_velocity_z_ec))};
            if (!common_angular_velocity_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure angular_velocity_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_angular_velocity_z = "angular_velocity_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_angular_velocity_z;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_angular_velocity_z = TypeObjectUtils::build_complete_member_detail(name_angular_velocity_z, member_ann_builtin_angular_velocity_z, ann_custom_IMUData);
            CompleteStructMember member_angular_velocity_z = TypeObjectUtils::build_complete_struct_member(common_angular_velocity_z, detail_angular_velocity_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_angular_velocity_z);
        }
        {
            TypeIdentifierPair type_ids_linear_acceleration_x;
            ReturnCode_t return_code_linear_acceleration_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_linear_acceleration_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_linear_acceleration_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_linear_acceleration_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "linear_acceleration_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_linear_acceleration_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_linear_acceleration_x = 0x00000007;
            bool common_linear_acceleration_x_ec {false};
            CommonStructMember common_linear_acceleration_x {TypeObjectUtils::build_common_struct_member(member_id_linear_acceleration_x, member_flags_linear_acceleration_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_linear_acceleration_x, common_linear_acceleration_x_ec))};
            if (!common_linear_acceleration_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure linear_acceleration_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_linear_acceleration_x = "linear_acceleration_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_linear_acceleration_x;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_linear_acceleration_x = TypeObjectUtils::build_complete_member_detail(name_linear_acceleration_x, member_ann_builtin_linear_acceleration_x, ann_custom_IMUData);
            CompleteStructMember member_linear_acceleration_x = TypeObjectUtils::build_complete_struct_member(common_linear_acceleration_x, detail_linear_acceleration_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_linear_acceleration_x);
        }
        {
            TypeIdentifierPair type_ids_linear_acceleration_y;
            ReturnCode_t return_code_linear_acceleration_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_linear_acceleration_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_linear_acceleration_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_linear_acceleration_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "linear_acceleration_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_linear_acceleration_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_linear_acceleration_y = 0x00000008;
            bool common_linear_acceleration_y_ec {false};
            CommonStructMember common_linear_acceleration_y {TypeObjectUtils::build_common_struct_member(member_id_linear_acceleration_y, member_flags_linear_acceleration_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_linear_acceleration_y, common_linear_acceleration_y_ec))};
            if (!common_linear_acceleration_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure linear_acceleration_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_linear_acceleration_y = "linear_acceleration_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_linear_acceleration_y;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_linear_acceleration_y = TypeObjectUtils::build_complete_member_detail(name_linear_acceleration_y, member_ann_builtin_linear_acceleration_y, ann_custom_IMUData);
            CompleteStructMember member_linear_acceleration_y = TypeObjectUtils::build_complete_struct_member(common_linear_acceleration_y, detail_linear_acceleration_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_linear_acceleration_y);
        }
        {
            TypeIdentifierPair type_ids_linear_acceleration_z;
            ReturnCode_t return_code_linear_acceleration_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_linear_acceleration_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_linear_acceleration_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_linear_acceleration_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "linear_acceleration_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_linear_acceleration_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_linear_acceleration_z = 0x00000009;
            bool common_linear_acceleration_z_ec {false};
            CommonStructMember common_linear_acceleration_z {TypeObjectUtils::build_common_struct_member(member_id_linear_acceleration_z, member_flags_linear_acceleration_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_linear_acceleration_z, common_linear_acceleration_z_ec))};
            if (!common_linear_acceleration_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure linear_acceleration_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_linear_acceleration_z = "linear_acceleration_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_linear_acceleration_z;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_linear_acceleration_z = TypeObjectUtils::build_complete_member_detail(name_linear_acceleration_z, member_ann_builtin_linear_acceleration_z, ann_custom_IMUData);
            CompleteStructMember member_linear_acceleration_z = TypeObjectUtils::build_complete_struct_member(common_linear_acceleration_z, detail_linear_acceleration_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_linear_acceleration_z);
        }
        {
            TypeIdentifierPair type_ids_roll;
            ReturnCode_t return_code_roll {eprosima::fastdds::dds::RETCODE_OK};
            return_code_roll =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_roll);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_roll)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "roll Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_roll = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_roll = 0x0000000a;
            bool common_roll_ec {false};
            CommonStructMember common_roll {TypeObjectUtils::build_common_struct_member(member_id_roll, member_flags_roll, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_roll, common_roll_ec))};
            if (!common_roll_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure roll member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_roll = "roll";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_roll;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_roll = TypeObjectUtils::build_complete_member_detail(name_roll, member_ann_builtin_roll, ann_custom_IMUData);
            CompleteStructMember member_roll = TypeObjectUtils::build_complete_struct_member(common_roll, detail_roll);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_roll);
        }
        {
            TypeIdentifierPair type_ids_pitch;
            ReturnCode_t return_code_pitch {eprosima::fastdds::dds::RETCODE_OK};
            return_code_pitch =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_pitch);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_pitch)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "pitch Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_pitch = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_pitch = 0x0000000b;
            bool common_pitch_ec {false};
            CommonStructMember common_pitch {TypeObjectUtils::build_common_struct_member(member_id_pitch, member_flags_pitch, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pitch, common_pitch_ec))};
            if (!common_pitch_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure pitch member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_pitch = "pitch";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_pitch;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_pitch = TypeObjectUtils::build_complete_member_detail(name_pitch, member_ann_builtin_pitch, ann_custom_IMUData);
            CompleteStructMember member_pitch = TypeObjectUtils::build_complete_struct_member(common_pitch, detail_pitch);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_pitch);
        }
        {
            TypeIdentifierPair type_ids_yaw;
            ReturnCode_t return_code_yaw {eprosima::fastdds::dds::RETCODE_OK};
            return_code_yaw =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_yaw);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_yaw)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "yaw Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_yaw = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_yaw = 0x0000000c;
            bool common_yaw_ec {false};
            CommonStructMember common_yaw {TypeObjectUtils::build_common_struct_member(member_id_yaw, member_flags_yaw, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_yaw, common_yaw_ec))};
            if (!common_yaw_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure yaw member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_yaw = "yaw";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_yaw;
            ann_custom_IMUData.reset();
            CompleteMemberDetail detail_yaw = TypeObjectUtils::build_complete_member_detail(name_yaw, member_ann_builtin_yaw, ann_custom_IMUData);
            CompleteStructMember member_yaw = TypeObjectUtils::build_complete_struct_member(common_yaw, detail_yaw);
            TypeObjectUtils::add_complete_struct_member(member_seq_IMUData, member_yaw);
        }
        CompleteStructType struct_type_IMUData = TypeObjectUtils::build_complete_struct_type(struct_flags_IMUData, header_IMUData, member_seq_IMUData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_IMUData, type_name_IMUData.to_string(), type_ids_IMUData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "imu_topic_base::IMUData already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace imu_topic_base

