// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file image_topic_base.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__IMAGE_TOPIC_BASE_IMAGE_TOPIC_BASE_HPP
#define FAST_DDS_GENERATED__IMAGE_TOPIC_BASE_IMAGE_TOPIC_BASE_HPP

#include <array>
#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(IMAGE_TOPIC_BASE_SOURCE)
#define IMAGE_TOPIC_BASE_DllAPI __declspec( dllexport )
#else
#define IMAGE_TOPIC_BASE_DllAPI __declspec( dllimport )
#endif // IMAGE_TOPIC_BASE_SOURCE
#else
#define IMAGE_TOPIC_BASE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define IMAGE_TOPIC_BASE_DllAPI
#endif // _WIN32

namespace image_topic_base {

const uint32_t MAX_IMAGE_BYTES = 640*480*5;
/*!
 * @brief This class represents the structure ImageData defined by the user in the IDL file.
 * @ingroup image_topic_base
 */
class ImageData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ImageData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ImageData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData(
            const ImageData& x)
    {
                    m_height = x.m_height;

                    m_width = x.m_width;

                    m_encoding = x.m_encoding;

                    m_step = x.m_step;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData(
            ImageData&& x) noexcept
    {
        m_height = x.m_height;
        m_width = x.m_width;
        m_encoding = x.m_encoding;
        m_step = x.m_step;
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData& operator =(
            const ImageData& x)
    {

                    m_height = x.m_height;

                    m_width = x.m_width;

                    m_encoding = x.m_encoding;

                    m_step = x.m_step;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ImageData that will be copied.
     */
    eProsima_user_DllExport ImageData& operator =(
            ImageData&& x) noexcept
    {

        m_height = x.m_height;
        m_width = x.m_width;
        m_encoding = x.m_encoding;
        m_step = x.m_step;
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ImageData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ImageData& x) const
    {
        return (m_height == x.m_height &&
           m_width == x.m_width &&
           m_encoding == x.m_encoding &&
           m_step == x.m_step &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x ImageData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ImageData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member height
     * @param _height New value for member height
     */
    eProsima_user_DllExport void height(
            uint16_t _height)
    {
        m_height = _height;
    }

    /*!
     * @brief This function returns the value of member height
     * @return Value of member height
     */
    eProsima_user_DllExport uint16_t height() const
    {
        return m_height;
    }

    /*!
     * @brief This function returns a reference to member height
     * @return Reference to member height
     */
    eProsima_user_DllExport uint16_t& height()
    {
        return m_height;
    }


    /*!
     * @brief This function sets a value in member width
     * @param _width New value for member width
     */
    eProsima_user_DllExport void width(
            uint16_t _width)
    {
        m_width = _width;
    }

    /*!
     * @brief This function returns the value of member width
     * @return Value of member width
     */
    eProsima_user_DllExport uint16_t width() const
    {
        return m_width;
    }

    /*!
     * @brief This function returns a reference to member width
     * @return Reference to member width
     */
    eProsima_user_DllExport uint16_t& width()
    {
        return m_width;
    }


    /*!
     * @brief This function sets a value in member encoding
     * @param _encoding New value for member encoding
     */
    eProsima_user_DllExport void encoding(
            uint8_t _encoding)
    {
        m_encoding = _encoding;
    }

    /*!
     * @brief This function returns the value of member encoding
     * @return Value of member encoding
     */
    eProsima_user_DllExport uint8_t encoding() const
    {
        return m_encoding;
    }

    /*!
     * @brief This function returns a reference to member encoding
     * @return Reference to member encoding
     */
    eProsima_user_DllExport uint8_t& encoding()
    {
        return m_encoding;
    }


    /*!
     * @brief This function sets a value in member step
     * @param _step New value for member step
     */
    eProsima_user_DllExport void step(
            uint32_t _step)
    {
        m_step = _step;
    }

    /*!
     * @brief This function returns the value of member step
     * @return Value of member step
     */
    eProsima_user_DllExport uint32_t step() const
    {
        return m_step;
    }

    /*!
     * @brief This function returns a reference to member step
     * @return Reference to member step
     */
    eProsima_user_DllExport uint32_t& step()
    {
        return m_step;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::array<uint8_t, MAX_IMAGE_BYTES>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::array<uint8_t, MAX_IMAGE_BYTES>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::array<uint8_t, MAX_IMAGE_BYTES>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::array<uint8_t, MAX_IMAGE_BYTES>& data()
    {
        return m_data;
    }



private:

    uint16_t m_height{0};
    uint16_t m_width{0};
    uint8_t m_encoding{0};
    uint32_t m_step{0};
    std::array<uint8_t, MAX_IMAGE_BYTES> m_data{0};

};

} // namespace image_topic_base

#endif // _FAST_DDS_GENERATED_IMAGE_TOPIC_BASE_IMAGE_TOPIC_BASE_HPP_


