// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file image_topic_baseTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "image_topic_baseTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "image_topic_base.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace image_topic_base {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ImageData_type_identifier(
        TypeIdentifierPair& type_ids_ImageData)
{

    ReturnCode_t return_code_ImageData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ImageData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "image_topic_base::ImageData", type_ids_ImageData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ImageData)
    {
        StructTypeFlag struct_flags_ImageData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_ImageData = "image_topic_base::ImageData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ImageData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ImageData;
        AppliedAnnotationSeq tmp_ann_custom_ImageData;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_ImageData;
        if (!tmp_ann_custom_ImageData.empty())
        {
            ann_custom_ImageData = tmp_ann_custom_ImageData;
        }

        CompleteTypeDetail detail_ImageData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ImageData, ann_custom_ImageData, type_name_ImageData.to_string());
        CompleteStructHeader header_ImageData;
        header_ImageData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ImageData);
        CompleteStructMemberSeq member_seq_ImageData;
        {
            TypeIdentifierPair type_ids_height;
            ReturnCode_t return_code_height {eprosima::fastdds::dds::RETCODE_OK};
            return_code_height =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_height);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_height)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "height Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_height = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_height = 0x00000000;
            bool common_height_ec {false};
            CommonStructMember common_height {TypeObjectUtils::build_common_struct_member(member_id_height, member_flags_height, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_height, common_height_ec))};
            if (!common_height_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure height member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_height = "height";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_height;
            ann_custom_ImageData.reset();
            CompleteMemberDetail detail_height = TypeObjectUtils::build_complete_member_detail(name_height, member_ann_builtin_height, ann_custom_ImageData);
            CompleteStructMember member_height = TypeObjectUtils::build_complete_struct_member(common_height, detail_height);
            TypeObjectUtils::add_complete_struct_member(member_seq_ImageData, member_height);
        }
        {
            TypeIdentifierPair type_ids_width;
            ReturnCode_t return_code_width {eprosima::fastdds::dds::RETCODE_OK};
            return_code_width =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint16_t", type_ids_width);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_width)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "width Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_width = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_width = 0x00000001;
            bool common_width_ec {false};
            CommonStructMember common_width {TypeObjectUtils::build_common_struct_member(member_id_width, member_flags_width, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_width, common_width_ec))};
            if (!common_width_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure width member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_width = "width";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_width;
            ann_custom_ImageData.reset();
            CompleteMemberDetail detail_width = TypeObjectUtils::build_complete_member_detail(name_width, member_ann_builtin_width, ann_custom_ImageData);
            CompleteStructMember member_width = TypeObjectUtils::build_complete_struct_member(common_width, detail_width);
            TypeObjectUtils::add_complete_struct_member(member_seq_ImageData, member_width);
        }
        {
            TypeIdentifierPair type_ids_encoding;
            ReturnCode_t return_code_encoding {eprosima::fastdds::dds::RETCODE_OK};
            return_code_encoding =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint8_t", type_ids_encoding);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_encoding)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "encoding Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_encoding = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_encoding = 0x00000002;
            bool common_encoding_ec {false};
            CommonStructMember common_encoding {TypeObjectUtils::build_common_struct_member(member_id_encoding, member_flags_encoding, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_encoding, common_encoding_ec))};
            if (!common_encoding_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure encoding member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_encoding = "encoding";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_encoding;
            ann_custom_ImageData.reset();
            CompleteMemberDetail detail_encoding = TypeObjectUtils::build_complete_member_detail(name_encoding, member_ann_builtin_encoding, ann_custom_ImageData);
            CompleteStructMember member_encoding = TypeObjectUtils::build_complete_struct_member(common_encoding, detail_encoding);
            TypeObjectUtils::add_complete_struct_member(member_seq_ImageData, member_encoding);
        }
        {
            TypeIdentifierPair type_ids_step;
            ReturnCode_t return_code_step {eprosima::fastdds::dds::RETCODE_OK};
            return_code_step =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_step);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_step)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "step Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_step = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_step = 0x00000003;
            bool common_step_ec {false};
            CommonStructMember common_step {TypeObjectUtils::build_common_struct_member(member_id_step, member_flags_step, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_step, common_step_ec))};
            if (!common_step_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure step member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_step = "step";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_step;
            ann_custom_ImageData.reset();
            CompleteMemberDetail detail_step = TypeObjectUtils::build_complete_member_detail(name_step, member_ann_builtin_step, ann_custom_ImageData);
            CompleteStructMember member_step = TypeObjectUtils::build_complete_struct_member(common_step, detail_step);
            TypeObjectUtils::add_complete_struct_member(member_seq_ImageData, member_step);
        }
        {
            TypeIdentifierPair type_ids_data;
            ReturnCode_t return_code_data {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint8_t_1536000", type_ids_data);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
            {
                return_code_data =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_uint8_t", type_ids_data);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint8_t_1536000_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint8_t_1536000 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, element_identifier_anonymous_array_uint8_t_1536000_ec))};
                if (!element_identifier_anonymous_array_uint8_t_1536000_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint8_t_1536000 = EK_COMPLETE;
                if (TK_NONE == type_ids_data.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint8_t_1536000 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint8_t_1536000 = 0;
                PlainCollectionHeader header_anonymous_array_uint8_t_1536000 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint8_t_1536000, element_flags_anonymous_array_uint8_t_1536000);
                {
                    LBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<LBound>(1536000));

                    PlainArrayLElemDefn array_ldefn = TypeObjectUtils::build_plain_array_l_elem_defn(header_anonymous_array_uint8_t_1536000, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint8_t_1536000));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_l_array_type_identifier(array_ldefn, "anonymous_array_uint8_t_1536000", type_ids_data))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint8_t_1536000 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data = 0x00000004;
            bool common_data_ec {false};
            CommonStructMember common_data {TypeObjectUtils::build_common_struct_member(member_id_data, member_flags_data, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
            if (!common_data_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data = "data";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
            ann_custom_ImageData.reset();
            CompleteMemberDetail detail_data = TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_ImageData);
            CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
            TypeObjectUtils::add_complete_struct_member(member_seq_ImageData, member_data);
        }
        CompleteStructType struct_type_ImageData = TypeObjectUtils::build_complete_struct_type(struct_flags_ImageData, header_ImageData, member_seq_ImageData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ImageData, type_name_ImageData.to_string(), type_ids_ImageData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "image_topic_base::ImageData already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace image_topic_base

