// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file motor_state_16TypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "motor_state_16TypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "motor_state_16.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace Motor_State_16 {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_motor_state_type_identifier(
        TypeIdentifierPair& type_ids_motor_state)
{

    ReturnCode_t return_code_motor_state {eprosima::fastdds::dds::RETCODE_OK};
    return_code_motor_state =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Motor_State_16::motor_state", type_ids_motor_state);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_motor_state)
    {
        StructTypeFlag struct_flags_motor_state = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_motor_state = "Motor_State_16::motor_state";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_motor_state;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_motor_state;
        AppliedAnnotationSeq tmp_ann_custom_motor_state;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_motor_state;
        if (!tmp_ann_custom_motor_state.empty())
        {
            ann_custom_motor_state = tmp_ann_custom_motor_state;
        }

        CompleteTypeDetail detail_motor_state = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_motor_state, ann_custom_motor_state, type_name_motor_state.to_string());
        CompleteStructHeader header_motor_state;
        header_motor_state = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_motor_state);
        CompleteStructMemberSeq member_seq_motor_state;
        {
            TypeIdentifierPair type_ids_motorId;
            ReturnCode_t return_code_motorId {eprosima::fastdds::dds::RETCODE_OK};
            return_code_motorId =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint32_t_16", type_ids_motorId);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_motorId)
            {
                return_code_motorId =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_uint32_t", type_ids_motorId);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_motorId)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint32_t_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint32_t_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_motorId, element_identifier_anonymous_array_uint32_t_16_ec))};
                if (!element_identifier_anonymous_array_uint32_t_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint32_t_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_motorId.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint32_t_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint32_t_16 = 0;
                PlainCollectionHeader header_anonymous_array_uint32_t_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint32_t_16, element_flags_anonymous_array_uint32_t_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_uint32_t_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint32_t_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_uint32_t_16", type_ids_motorId))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint32_t_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_motorId = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_motorId = 0x00000000;
            bool common_motorId_ec {false};
            CommonStructMember common_motorId {TypeObjectUtils::build_common_struct_member(member_id_motorId, member_flags_motorId, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_motorId, common_motorId_ec))};
            if (!common_motorId_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure motorId member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_motorId = "motorId";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_motorId;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_motorId = TypeObjectUtils::build_complete_member_detail(name_motorId, member_ann_builtin_motorId, ann_custom_motor_state);
            CompleteStructMember member_motorId = TypeObjectUtils::build_complete_struct_member(common_motorId, detail_motorId);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_motorId);
        }
        {
            TypeIdentifierPair type_ids_lastSeenTime;
            ReturnCode_t return_code_lastSeenTime {eprosima::fastdds::dds::RETCODE_OK};
            return_code_lastSeenTime =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_int64_t_16", type_ids_lastSeenTime);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_lastSeenTime)
            {
                return_code_lastSeenTime =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_int64_t", type_ids_lastSeenTime);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_lastSeenTime)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_int64_t_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_int64_t_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_lastSeenTime, element_identifier_anonymous_array_int64_t_16_ec))};
                if (!element_identifier_anonymous_array_int64_t_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_int64_t_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_lastSeenTime.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_int64_t_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_int64_t_16 = 0;
                PlainCollectionHeader header_anonymous_array_int64_t_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_int64_t_16, element_flags_anonymous_array_int64_t_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_int64_t_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_int64_t_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_int64_t_16", type_ids_lastSeenTime))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_int64_t_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_lastSeenTime = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_lastSeenTime = 0x00000001;
            bool common_lastSeenTime_ec {false};
            CommonStructMember common_lastSeenTime {TypeObjectUtils::build_common_struct_member(member_id_lastSeenTime, member_flags_lastSeenTime, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_lastSeenTime, common_lastSeenTime_ec))};
            if (!common_lastSeenTime_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure lastSeenTime member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_lastSeenTime = "lastSeenTime";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_lastSeenTime;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_lastSeenTime = TypeObjectUtils::build_complete_member_detail(name_lastSeenTime, member_ann_builtin_lastSeenTime, ann_custom_motor_state);
            CompleteStructMember member_lastSeenTime = TypeObjectUtils::build_complete_struct_member(common_lastSeenTime, detail_lastSeenTime);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_lastSeenTime);
        }
        {
            TypeIdentifierPair type_ids_status;
            ReturnCode_t return_code_status {eprosima::fastdds::dds::RETCODE_OK};
            return_code_status =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint8_t_16", type_ids_status);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_status)
            {
                return_code_status =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_uint8_t", type_ids_status);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_status)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint8_t_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint8_t_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status, element_identifier_anonymous_array_uint8_t_16_ec))};
                if (!element_identifier_anonymous_array_uint8_t_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint8_t_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_status.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint8_t_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint8_t_16 = 0;
                PlainCollectionHeader header_anonymous_array_uint8_t_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint8_t_16, element_flags_anonymous_array_uint8_t_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_uint8_t_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint8_t_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_uint8_t_16", type_ids_status))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint8_t_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_status = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_status = 0x00000002;
            bool common_status_ec {false};
            CommonStructMember common_status {TypeObjectUtils::build_common_struct_member(member_id_status, member_flags_status, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_status, common_status_ec))};
            if (!common_status_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure status member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_status = "status";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_status;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_status = TypeObjectUtils::build_complete_member_detail(name_status, member_ann_builtin_status, ann_custom_motor_state);
            CompleteStructMember member_status = TypeObjectUtils::build_complete_struct_member(common_status, detail_status);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_status);
        }
        {
            TypeIdentifierPair type_ids_position;
            ReturnCode_t return_code_position {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_position);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position)
            {
                return_code_position =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_position);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_position)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_position.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_position))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_position = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position = 0x00000003;
            bool common_position_ec {false};
            CommonStructMember common_position {TypeObjectUtils::build_common_struct_member(member_id_position, member_flags_position, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position, common_position_ec))};
            if (!common_position_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position = "position";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_position = TypeObjectUtils::build_complete_member_detail(name_position, member_ann_builtin_position, ann_custom_motor_state);
            CompleteStructMember member_position = TypeObjectUtils::build_complete_struct_member(common_position, detail_position);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_position);
        }
        {
            TypeIdentifierPair type_ids_speed;
            ReturnCode_t return_code_speed {eprosima::fastdds::dds::RETCODE_OK};
            return_code_speed =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_speed);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed)
            {
                return_code_speed =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_speed);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_speed)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_speed.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_speed))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_speed = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_speed = 0x00000004;
            bool common_speed_ec {false};
            CommonStructMember common_speed {TypeObjectUtils::build_common_struct_member(member_id_speed, member_flags_speed, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_speed, common_speed_ec))};
            if (!common_speed_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure speed member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_speed = "speed";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_speed;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_speed = TypeObjectUtils::build_complete_member_detail(name_speed, member_ann_builtin_speed, ann_custom_motor_state);
            CompleteStructMember member_speed = TypeObjectUtils::build_complete_struct_member(common_speed, detail_speed);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_speed);
        }
        {
            TypeIdentifierPair type_ids_current;
            ReturnCode_t return_code_current {eprosima::fastdds::dds::RETCODE_OK};
            return_code_current =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_current);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_current)
            {
                return_code_current =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_current);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_current)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_current.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_current))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_current = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_current = 0x00000005;
            bool common_current_ec {false};
            CommonStructMember common_current {TypeObjectUtils::build_common_struct_member(member_id_current, member_flags_current, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_current, common_current_ec))};
            if (!common_current_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure current member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_current = "current";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_current;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_current = TypeObjectUtils::build_complete_member_detail(name_current, member_ann_builtin_current, ann_custom_motor_state);
            CompleteStructMember member_current = TypeObjectUtils::build_complete_struct_member(common_current, detail_current);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_current);
        }
        {
            TypeIdentifierPair type_ids_motorTemperature;
            ReturnCode_t return_code_motorTemperature {eprosima::fastdds::dds::RETCODE_OK};
            return_code_motorTemperature =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_motorTemperature);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_motorTemperature)
            {
                return_code_motorTemperature =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_motorTemperature);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_motorTemperature)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_motorTemperature, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_motorTemperature.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_motorTemperature))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_motorTemperature = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_motorTemperature = 0x00000006;
            bool common_motorTemperature_ec {false};
            CommonStructMember common_motorTemperature {TypeObjectUtils::build_common_struct_member(member_id_motorTemperature, member_flags_motorTemperature, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_motorTemperature, common_motorTemperature_ec))};
            if (!common_motorTemperature_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure motorTemperature member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_motorTemperature = "motorTemperature";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_motorTemperature;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_motorTemperature = TypeObjectUtils::build_complete_member_detail(name_motorTemperature, member_ann_builtin_motorTemperature, ann_custom_motor_state);
            CompleteStructMember member_motorTemperature = TypeObjectUtils::build_complete_struct_member(common_motorTemperature, detail_motorTemperature);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_motorTemperature);
        }
        {
            TypeIdentifierPair type_ids_mosTemperature;
            ReturnCode_t return_code_mosTemperature {eprosima::fastdds::dds::RETCODE_OK};
            return_code_mosTemperature =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_mosTemperature);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_mosTemperature)
            {
                return_code_mosTemperature =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_mosTemperature);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_mosTemperature)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_mosTemperature, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_mosTemperature.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_mosTemperature))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_mosTemperature = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_mosTemperature = 0x00000007;
            bool common_mosTemperature_ec {false};
            CommonStructMember common_mosTemperature {TypeObjectUtils::build_common_struct_member(member_id_mosTemperature, member_flags_mosTemperature, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_mosTemperature, common_mosTemperature_ec))};
            if (!common_mosTemperature_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure mosTemperature member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_mosTemperature = "mosTemperature";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_mosTemperature;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_mosTemperature = TypeObjectUtils::build_complete_member_detail(name_mosTemperature, member_ann_builtin_mosTemperature, ann_custom_motor_state);
            CompleteStructMember member_mosTemperature = TypeObjectUtils::build_complete_struct_member(common_mosTemperature, detail_mosTemperature);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_mosTemperature);
        }
        {
            TypeIdentifierPair type_ids_isonline;
            ReturnCode_t return_code_isonline {eprosima::fastdds::dds::RETCODE_OK};
            return_code_isonline =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_bool_16", type_ids_isonline);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_isonline)
            {
                return_code_isonline =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_bool", type_ids_isonline);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_isonline)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_bool_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_bool_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_isonline, element_identifier_anonymous_array_bool_16_ec))};
                if (!element_identifier_anonymous_array_bool_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_bool_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_isonline.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_bool_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_bool_16 = 0;
                PlainCollectionHeader header_anonymous_array_bool_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_bool_16, element_flags_anonymous_array_bool_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_bool_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_bool_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_bool_16", type_ids_isonline))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_bool_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_isonline = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_isonline = 0x00000008;
            bool common_isonline_ec {false};
            CommonStructMember common_isonline {TypeObjectUtils::build_common_struct_member(member_id_isonline, member_flags_isonline, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_isonline, common_isonline_ec))};
            if (!common_isonline_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure isonline member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_isonline = "isonline";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_isonline;
            ann_custom_motor_state.reset();
            CompleteMemberDetail detail_isonline = TypeObjectUtils::build_complete_member_detail(name_isonline, member_ann_builtin_isonline, ann_custom_motor_state);
            CompleteStructMember member_isonline = TypeObjectUtils::build_complete_struct_member(common_isonline, detail_isonline);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_state, member_isonline);
        }
        CompleteStructType struct_type_motor_state = TypeObjectUtils::build_complete_struct_type(struct_flags_motor_state, header_motor_state, member_seq_motor_state);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_motor_state, type_name_motor_state.to_string(), type_ids_motor_state))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Motor_State_16::motor_state already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Motor_State_16

