// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file motor_state_16.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__MOTOR_STATE_16_MOTOR_STATE_16_HPP
#define FAST_DDS_GENERATED__MOTOR_STATE_16_MOTOR_STATE_16_HPP

#include <array>
#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTOR_STATE_16_SOURCE)
#define MOTOR_STATE_16_DllAPI __declspec( dllexport )
#else
#define MOTOR_STATE_16_DllAPI __declspec( dllimport )
#endif // MOTOR_STATE_16_SOURCE
#else
#define MOTOR_STATE_16_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTOR_STATE_16_DllAPI
#endif // _WIN32

namespace Motor_State_16 {

/*!
 * @brief This class represents the structure motor_state defined by the user in the IDL file.
 * @ingroup motor_state_16
 */
class motor_state
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport motor_state()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~motor_state()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object motor_state that will be copied.
     */
    eProsima_user_DllExport motor_state(
            const motor_state& x)
    {
                    m_motorId = x.m_motorId;

                    m_lastSeenTime = x.m_lastSeenTime;

                    m_status = x.m_status;

                    m_position = x.m_position;

                    m_speed = x.m_speed;

                    m_current = x.m_current;

                    m_motorTemperature = x.m_motorTemperature;

                    m_mosTemperature = x.m_mosTemperature;

                    m_isonline = x.m_isonline;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object motor_state that will be copied.
     */
    eProsima_user_DllExport motor_state(
            motor_state&& x) noexcept
    {
        m_motorId = std::move(x.m_motorId);
        m_lastSeenTime = std::move(x.m_lastSeenTime);
        m_status = std::move(x.m_status);
        m_position = std::move(x.m_position);
        m_speed = std::move(x.m_speed);
        m_current = std::move(x.m_current);
        m_motorTemperature = std::move(x.m_motorTemperature);
        m_mosTemperature = std::move(x.m_mosTemperature);
        m_isonline = std::move(x.m_isonline);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object motor_state that will be copied.
     */
    eProsima_user_DllExport motor_state& operator =(
            const motor_state& x)
    {

                    m_motorId = x.m_motorId;

                    m_lastSeenTime = x.m_lastSeenTime;

                    m_status = x.m_status;

                    m_position = x.m_position;

                    m_speed = x.m_speed;

                    m_current = x.m_current;

                    m_motorTemperature = x.m_motorTemperature;

                    m_mosTemperature = x.m_mosTemperature;

                    m_isonline = x.m_isonline;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object motor_state that will be copied.
     */
    eProsima_user_DllExport motor_state& operator =(
            motor_state&& x) noexcept
    {

        m_motorId = std::move(x.m_motorId);
        m_lastSeenTime = std::move(x.m_lastSeenTime);
        m_status = std::move(x.m_status);
        m_position = std::move(x.m_position);
        m_speed = std::move(x.m_speed);
        m_current = std::move(x.m_current);
        m_motorTemperature = std::move(x.m_motorTemperature);
        m_mosTemperature = std::move(x.m_mosTemperature);
        m_isonline = std::move(x.m_isonline);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x motor_state object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const motor_state& x) const
    {
        return (m_motorId == x.m_motorId &&
           m_lastSeenTime == x.m_lastSeenTime &&
           m_status == x.m_status &&
           m_position == x.m_position &&
           m_speed == x.m_speed &&
           m_current == x.m_current &&
           m_motorTemperature == x.m_motorTemperature &&
           m_mosTemperature == x.m_mosTemperature &&
           m_isonline == x.m_isonline);
    }

    /*!
     * @brief Comparison operator.
     * @param x motor_state object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const motor_state& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member motorId
     * @param _motorId New value to be copied in member motorId
     */
    eProsima_user_DllExport void motorId(
            const std::array<uint32_t, 16>& _motorId)
    {
        m_motorId = _motorId;
    }

    /*!
     * @brief This function moves the value in member motorId
     * @param _motorId New value to be moved in member motorId
     */
    eProsima_user_DllExport void motorId(
            std::array<uint32_t, 16>&& _motorId)
    {
        m_motorId = std::move(_motorId);
    }

    /*!
     * @brief This function returns a constant reference to member motorId
     * @return Constant reference to member motorId
     */
    eProsima_user_DllExport const std::array<uint32_t, 16>& motorId() const
    {
        return m_motorId;
    }

    /*!
     * @brief This function returns a reference to member motorId
     * @return Reference to member motorId
     */
    eProsima_user_DllExport std::array<uint32_t, 16>& motorId()
    {
        return m_motorId;
    }


    /*!
     * @brief This function copies the value in member lastSeenTime
     * @param _lastSeenTime New value to be copied in member lastSeenTime
     */
    eProsima_user_DllExport void lastSeenTime(
            const std::array<int64_t, 16>& _lastSeenTime)
    {
        m_lastSeenTime = _lastSeenTime;
    }

    /*!
     * @brief This function moves the value in member lastSeenTime
     * @param _lastSeenTime New value to be moved in member lastSeenTime
     */
    eProsima_user_DllExport void lastSeenTime(
            std::array<int64_t, 16>&& _lastSeenTime)
    {
        m_lastSeenTime = std::move(_lastSeenTime);
    }

    /*!
     * @brief This function returns a constant reference to member lastSeenTime
     * @return Constant reference to member lastSeenTime
     */
    eProsima_user_DllExport const std::array<int64_t, 16>& lastSeenTime() const
    {
        return m_lastSeenTime;
    }

    /*!
     * @brief This function returns a reference to member lastSeenTime
     * @return Reference to member lastSeenTime
     */
    eProsima_user_DllExport std::array<int64_t, 16>& lastSeenTime()
    {
        return m_lastSeenTime;
    }


    /*!
     * @brief This function copies the value in member status
     * @param _status New value to be copied in member status
     */
    eProsima_user_DllExport void status(
            const std::array<uint8_t, 16>& _status)
    {
        m_status = _status;
    }

    /*!
     * @brief This function moves the value in member status
     * @param _status New value to be moved in member status
     */
    eProsima_user_DllExport void status(
            std::array<uint8_t, 16>&& _status)
    {
        m_status = std::move(_status);
    }

    /*!
     * @brief This function returns a constant reference to member status
     * @return Constant reference to member status
     */
    eProsima_user_DllExport const std::array<uint8_t, 16>& status() const
    {
        return m_status;
    }

    /*!
     * @brief This function returns a reference to member status
     * @return Reference to member status
     */
    eProsima_user_DllExport std::array<uint8_t, 16>& status()
    {
        return m_status;
    }


    /*!
     * @brief This function copies the value in member position
     * @param _position New value to be copied in member position
     */
    eProsima_user_DllExport void position(
            const std::array<float, 16>& _position)
    {
        m_position = _position;
    }

    /*!
     * @brief This function moves the value in member position
     * @param _position New value to be moved in member position
     */
    eProsima_user_DllExport void position(
            std::array<float, 16>&& _position)
    {
        m_position = std::move(_position);
    }

    /*!
     * @brief This function returns a constant reference to member position
     * @return Constant reference to member position
     */
    eProsima_user_DllExport const std::array<float, 16>& position() const
    {
        return m_position;
    }

    /*!
     * @brief This function returns a reference to member position
     * @return Reference to member position
     */
    eProsima_user_DllExport std::array<float, 16>& position()
    {
        return m_position;
    }


    /*!
     * @brief This function copies the value in member speed
     * @param _speed New value to be copied in member speed
     */
    eProsima_user_DllExport void speed(
            const std::array<float, 16>& _speed)
    {
        m_speed = _speed;
    }

    /*!
     * @brief This function moves the value in member speed
     * @param _speed New value to be moved in member speed
     */
    eProsima_user_DllExport void speed(
            std::array<float, 16>&& _speed)
    {
        m_speed = std::move(_speed);
    }

    /*!
     * @brief This function returns a constant reference to member speed
     * @return Constant reference to member speed
     */
    eProsima_user_DllExport const std::array<float, 16>& speed() const
    {
        return m_speed;
    }

    /*!
     * @brief This function returns a reference to member speed
     * @return Reference to member speed
     */
    eProsima_user_DllExport std::array<float, 16>& speed()
    {
        return m_speed;
    }


    /*!
     * @brief This function copies the value in member current
     * @param _current New value to be copied in member current
     */
    eProsima_user_DllExport void current(
            const std::array<float, 16>& _current)
    {
        m_current = _current;
    }

    /*!
     * @brief This function moves the value in member current
     * @param _current New value to be moved in member current
     */
    eProsima_user_DllExport void current(
            std::array<float, 16>&& _current)
    {
        m_current = std::move(_current);
    }

    /*!
     * @brief This function returns a constant reference to member current
     * @return Constant reference to member current
     */
    eProsima_user_DllExport const std::array<float, 16>& current() const
    {
        return m_current;
    }

    /*!
     * @brief This function returns a reference to member current
     * @return Reference to member current
     */
    eProsima_user_DllExport std::array<float, 16>& current()
    {
        return m_current;
    }


    /*!
     * @brief This function copies the value in member motorTemperature
     * @param _motorTemperature New value to be copied in member motorTemperature
     */
    eProsima_user_DllExport void motorTemperature(
            const std::array<float, 16>& _motorTemperature)
    {
        m_motorTemperature = _motorTemperature;
    }

    /*!
     * @brief This function moves the value in member motorTemperature
     * @param _motorTemperature New value to be moved in member motorTemperature
     */
    eProsima_user_DllExport void motorTemperature(
            std::array<float, 16>&& _motorTemperature)
    {
        m_motorTemperature = std::move(_motorTemperature);
    }

    /*!
     * @brief This function returns a constant reference to member motorTemperature
     * @return Constant reference to member motorTemperature
     */
    eProsima_user_DllExport const std::array<float, 16>& motorTemperature() const
    {
        return m_motorTemperature;
    }

    /*!
     * @brief This function returns a reference to member motorTemperature
     * @return Reference to member motorTemperature
     */
    eProsima_user_DllExport std::array<float, 16>& motorTemperature()
    {
        return m_motorTemperature;
    }


    /*!
     * @brief This function copies the value in member mosTemperature
     * @param _mosTemperature New value to be copied in member mosTemperature
     */
    eProsima_user_DllExport void mosTemperature(
            const std::array<float, 16>& _mosTemperature)
    {
        m_mosTemperature = _mosTemperature;
    }

    /*!
     * @brief This function moves the value in member mosTemperature
     * @param _mosTemperature New value to be moved in member mosTemperature
     */
    eProsima_user_DllExport void mosTemperature(
            std::array<float, 16>&& _mosTemperature)
    {
        m_mosTemperature = std::move(_mosTemperature);
    }

    /*!
     * @brief This function returns a constant reference to member mosTemperature
     * @return Constant reference to member mosTemperature
     */
    eProsima_user_DllExport const std::array<float, 16>& mosTemperature() const
    {
        return m_mosTemperature;
    }

    /*!
     * @brief This function returns a reference to member mosTemperature
     * @return Reference to member mosTemperature
     */
    eProsima_user_DllExport std::array<float, 16>& mosTemperature()
    {
        return m_mosTemperature;
    }


    /*!
     * @brief This function copies the value in member isonline
     * @param _isonline New value to be copied in member isonline
     */
    eProsima_user_DllExport void isonline(
            const std::array<bool, 16>& _isonline)
    {
        m_isonline = _isonline;
    }

    /*!
     * @brief This function moves the value in member isonline
     * @param _isonline New value to be moved in member isonline
     */
    eProsima_user_DllExport void isonline(
            std::array<bool, 16>&& _isonline)
    {
        m_isonline = std::move(_isonline);
    }

    /*!
     * @brief This function returns a constant reference to member isonline
     * @return Constant reference to member isonline
     */
    eProsima_user_DllExport const std::array<bool, 16>& isonline() const
    {
        return m_isonline;
    }

    /*!
     * @brief This function returns a reference to member isonline
     * @return Reference to member isonline
     */
    eProsima_user_DllExport std::array<bool, 16>& isonline()
    {
        return m_isonline;
    }



private:

    std::array<uint32_t, 16> m_motorId{0};
    std::array<int64_t, 16> m_lastSeenTime{0};
    std::array<uint8_t, 16> m_status{0};
    std::array<float, 16> m_position{0.0};
    std::array<float, 16> m_speed{0.0};
    std::array<float, 16> m_current{0.0};
    std::array<float, 16> m_motorTemperature{0.0};
    std::array<float, 16> m_mosTemperature{0.0};
    std::array<bool, 16> m_isonline{false};

};

} // namespace Motor_State_16

#endif // _FAST_DDS_GENERATED_MOTOR_STATE_16_MOTOR_STATE_16_HPP_


