// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file elevmap_topic_baseTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "elevmap_topic_baseTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "elevmap_topic_base.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace elevmap_topic_base {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_LayerData_type_identifier(
        TypeIdentifierPair& type_ids_LayerData)
{

    ReturnCode_t return_code_LayerData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_LayerData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "elevmap_topic_base::LayerData", type_ids_LayerData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_LayerData)
    {
        StructTypeFlag struct_flags_LayerData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_LayerData = "elevmap_topic_base::LayerData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_LayerData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_LayerData;
        CompleteTypeDetail detail_LayerData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_LayerData, ann_custom_LayerData, type_name_LayerData.to_string());
        CompleteStructHeader header_LayerData;
        header_LayerData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_LayerData);
        CompleteStructMemberSeq member_seq_LayerData;
        {
            TypeIdentifierPair type_ids_name;
            ReturnCode_t return_code_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_32", type_ids_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_name)
            {
                {
                    SBound bound = static_cast<SBound>(32);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_32", type_ids_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_32 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_name = 0x00000000;
            bool common_name_ec {false};
            CommonStructMember common_name {TypeObjectUtils::build_common_struct_member(member_id_name, member_flags_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_name, common_name_ec))};
            if (!common_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_name = "name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_name;
            ann_custom_LayerData.reset();
            CompleteMemberDetail detail_name = TypeObjectUtils::build_complete_member_detail(name_name, member_ann_builtin_name, ann_custom_LayerData);
            CompleteStructMember member_name = TypeObjectUtils::build_complete_struct_member(common_name, detail_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_LayerData, member_name);
        }
        {
            TypeIdentifierPair type_ids_data;
            ReturnCode_t return_code_data {eprosima::fastdds::dds::RETCODE_OK};
            return_code_data =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_float_40000", type_ids_data);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
            {
                return_code_data =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_data);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_data)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_sequence_float_40000_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_float_40000 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, element_identifier_anonymous_sequence_float_40000_ec))};
                if (!element_identifier_anonymous_sequence_float_40000_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_float_40000 = EK_COMPLETE;
                if (TK_NONE == type_ids_data.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_float_40000 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_float_40000 = 0;
                PlainCollectionHeader header_anonymous_sequence_float_40000 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_float_40000, element_flags_anonymous_sequence_float_40000);
                {
                    LBound bound = 40000;
                    PlainSequenceLElemDefn seq_ldefn = TypeObjectUtils::build_plain_sequence_l_elem_defn(header_anonymous_sequence_float_40000, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_float_40000));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_l_sequence_type_identifier(seq_ldefn, "anonymous_sequence_float_40000", type_ids_data))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_float_40000 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_data = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_data = 0x00000001;
            bool common_data_ec {false};
            CommonStructMember common_data {TypeObjectUtils::build_common_struct_member(member_id_data, member_flags_data, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_data, common_data_ec))};
            if (!common_data_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure data member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_data = "data";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_data;
            ann_custom_LayerData.reset();
            CompleteMemberDetail detail_data = TypeObjectUtils::build_complete_member_detail(name_data, member_ann_builtin_data, ann_custom_LayerData);
            CompleteStructMember member_data = TypeObjectUtils::build_complete_struct_member(common_data, detail_data);
            TypeObjectUtils::add_complete_struct_member(member_seq_LayerData, member_data);
        }
        CompleteStructType struct_type_LayerData = TypeObjectUtils::build_complete_struct_type(struct_flags_LayerData, header_LayerData, member_seq_LayerData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_LayerData, type_name_LayerData.to_string(), type_ids_LayerData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "elevmap_topic_base::LayerData already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ElevMapData_type_identifier(
        TypeIdentifierPair& type_ids_ElevMapData)
{

    ReturnCode_t return_code_ElevMapData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ElevMapData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "elevmap_topic_base::ElevMapData", type_ids_ElevMapData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ElevMapData)
    {
        StructTypeFlag struct_flags_ElevMapData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_ElevMapData = "elevmap_topic_base::ElevMapData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ElevMapData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ElevMapData;
        AppliedAnnotationSeq tmp_ann_custom_ElevMapData;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_ElevMapData;
        if (!tmp_ann_custom_ElevMapData.empty())
        {
            ann_custom_ElevMapData = tmp_ann_custom_ElevMapData;
        }

        CompleteTypeDetail detail_ElevMapData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ElevMapData, ann_custom_ElevMapData, type_name_ElevMapData.to_string());
        CompleteStructHeader header_ElevMapData;
        header_ElevMapData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ElevMapData);
        CompleteStructMemberSeq member_seq_ElevMapData;
        {
            TypeIdentifierPair type_ids_frame_id;
            ReturnCode_t return_code_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_128", type_ids_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_id)
            {
                {
                    SBound bound = static_cast<SBound>(128);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_128", type_ids_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_128 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_id = 0x00000000;
            bool common_frame_id_ec {false};
            CommonStructMember common_frame_id {TypeObjectUtils::build_common_struct_member(member_id_frame_id, member_flags_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_id, common_frame_id_ec))};
            if (!common_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_id = "frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_id;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_frame_id = TypeObjectUtils::build_complete_member_detail(name_frame_id, member_ann_builtin_frame_id, ann_custom_ElevMapData);
            CompleteStructMember member_frame_id = TypeObjectUtils::build_complete_struct_member(common_frame_id, detail_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_frame_id);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000001;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_ElevMapData);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_resolution;
            ReturnCode_t return_code_resolution {eprosima::fastdds::dds::RETCODE_OK};
            return_code_resolution =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_resolution);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_resolution)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "resolution Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_resolution = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_resolution = 0x00000002;
            bool common_resolution_ec {false};
            CommonStructMember common_resolution {TypeObjectUtils::build_common_struct_member(member_id_resolution, member_flags_resolution, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_resolution, common_resolution_ec))};
            if (!common_resolution_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure resolution member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_resolution = "resolution";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_resolution;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_resolution = TypeObjectUtils::build_complete_member_detail(name_resolution, member_ann_builtin_resolution, ann_custom_ElevMapData);
            CompleteStructMember member_resolution = TypeObjectUtils::build_complete_struct_member(common_resolution, detail_resolution);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_resolution);
        }
        {
            TypeIdentifierPair type_ids_length_x;
            ReturnCode_t return_code_length_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_length_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_length_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_length_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "length_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_length_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_length_x = 0x00000003;
            bool common_length_x_ec {false};
            CommonStructMember common_length_x {TypeObjectUtils::build_common_struct_member(member_id_length_x, member_flags_length_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_length_x, common_length_x_ec))};
            if (!common_length_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure length_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_length_x = "length_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_length_x;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_length_x = TypeObjectUtils::build_complete_member_detail(name_length_x, member_ann_builtin_length_x, ann_custom_ElevMapData);
            CompleteStructMember member_length_x = TypeObjectUtils::build_complete_struct_member(common_length_x, detail_length_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_length_x);
        }
        {
            TypeIdentifierPair type_ids_length_y;
            ReturnCode_t return_code_length_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_length_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_length_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_length_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "length_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_length_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_length_y = 0x00000004;
            bool common_length_y_ec {false};
            CommonStructMember common_length_y {TypeObjectUtils::build_common_struct_member(member_id_length_y, member_flags_length_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_length_y, common_length_y_ec))};
            if (!common_length_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure length_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_length_y = "length_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_length_y;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_length_y = TypeObjectUtils::build_complete_member_detail(name_length_y, member_ann_builtin_length_y, ann_custom_ElevMapData);
            CompleteStructMember member_length_y = TypeObjectUtils::build_complete_struct_member(common_length_y, detail_length_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_length_y);
        }
        {
            TypeIdentifierPair type_ids_rows;
            ReturnCode_t return_code_rows {eprosima::fastdds::dds::RETCODE_OK};
            return_code_rows =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_rows);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_rows)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "rows Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_rows = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_rows = 0x00000005;
            bool common_rows_ec {false};
            CommonStructMember common_rows {TypeObjectUtils::build_common_struct_member(member_id_rows, member_flags_rows, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_rows, common_rows_ec))};
            if (!common_rows_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure rows member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_rows = "rows";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_rows;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_rows = TypeObjectUtils::build_complete_member_detail(name_rows, member_ann_builtin_rows, ann_custom_ElevMapData);
            CompleteStructMember member_rows = TypeObjectUtils::build_complete_struct_member(common_rows, detail_rows);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_rows);
        }
        {
            TypeIdentifierPair type_ids_cols;
            ReturnCode_t return_code_cols {eprosima::fastdds::dds::RETCODE_OK};
            return_code_cols =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint32_t", type_ids_cols);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_cols)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "cols Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_cols = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_cols = 0x00000006;
            bool common_cols_ec {false};
            CommonStructMember common_cols {TypeObjectUtils::build_common_struct_member(member_id_cols, member_flags_cols, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_cols, common_cols_ec))};
            if (!common_cols_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure cols member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_cols = "cols";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_cols;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_cols = TypeObjectUtils::build_complete_member_detail(name_cols, member_ann_builtin_cols, ann_custom_ElevMapData);
            CompleteStructMember member_cols = TypeObjectUtils::build_complete_struct_member(common_cols, detail_cols);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_cols);
        }
        {
            TypeIdentifierPair type_ids_layers;
            ReturnCode_t return_code_layers {eprosima::fastdds::dds::RETCODE_OK};
            return_code_layers =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_elevmap_topic_base_LayerData_4", type_ids_layers);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_layers)
            {
                return_code_layers =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "elevmap_topic_base::LayerData", type_ids_layers);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_layers)
                {
                    ::elevmap_topic_base::register_LayerData_type_identifier(type_ids_layers);
                }
                bool element_identifier_anonymous_sequence_elevmap_topic_base_LayerData_4_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_elevmap_topic_base_LayerData_4 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_layers, element_identifier_anonymous_sequence_elevmap_topic_base_LayerData_4_ec))};
                if (!element_identifier_anonymous_sequence_elevmap_topic_base_LayerData_4_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_elevmap_topic_base_LayerData_4 = EK_COMPLETE;
                if (TK_NONE == type_ids_layers.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_elevmap_topic_base_LayerData_4 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_elevmap_topic_base_LayerData_4 = 0;
                PlainCollectionHeader header_anonymous_sequence_elevmap_topic_base_LayerData_4 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_elevmap_topic_base_LayerData_4, element_flags_anonymous_sequence_elevmap_topic_base_LayerData_4);
                {
                    SBound bound = static_cast<SBound>(4);
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_elevmap_topic_base_LayerData_4, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_elevmap_topic_base_LayerData_4));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_elevmap_topic_base_LayerData_4", type_ids_layers))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_elevmap_topic_base_LayerData_4 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_layers = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_layers = 0x00000007;
            bool common_layers_ec {false};
            CommonStructMember common_layers {TypeObjectUtils::build_common_struct_member(member_id_layers, member_flags_layers, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_layers, common_layers_ec))};
            if (!common_layers_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure layers member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_layers = "layers";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_layers;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_layers = TypeObjectUtils::build_complete_member_detail(name_layers, member_ann_builtin_layers, ann_custom_ElevMapData);
            CompleteStructMember member_layers = TypeObjectUtils::build_complete_struct_member(common_layers, detail_layers);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_layers);
        }
        {
            TypeIdentifierPair type_ids_basic_layers;
            ReturnCode_t return_code_basic_layers {eprosima::fastdds::dds::RETCODE_OK};
            return_code_basic_layers =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_anonymous_string_32_4", type_ids_basic_layers);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_basic_layers)
            {
                return_code_basic_layers =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "anonymous_string_32", type_ids_basic_layers);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_basic_layers)
                {
                    {
                        SBound bound = static_cast<SBound>(32);
                        StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                                TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                                "anonymous_string_32", type_ids_basic_layers))
                        {
                            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                                "anonymous_string_32 already registered in TypeObjectRegistry for a different type.");
                        }
                    }
                }
                bool element_identifier_anonymous_sequence_anonymous_string_32_4_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_anonymous_string_32_4 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_basic_layers, element_identifier_anonymous_sequence_anonymous_string_32_4_ec))};
                if (!element_identifier_anonymous_sequence_anonymous_string_32_4_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_anonymous_string_32_4 = EK_COMPLETE;
                if (TK_NONE == type_ids_basic_layers.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_anonymous_string_32_4 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_anonymous_string_32_4 = 0;
                PlainCollectionHeader header_anonymous_sequence_anonymous_string_32_4 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_anonymous_string_32_4, element_flags_anonymous_sequence_anonymous_string_32_4);
                {
                    SBound bound = static_cast<SBound>(4);
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_anonymous_string_32_4, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_anonymous_string_32_4));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_anonymous_string_32_4", type_ids_basic_layers))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_anonymous_string_32_4 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_basic_layers = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_basic_layers = 0x00000008;
            bool common_basic_layers_ec {false};
            CommonStructMember common_basic_layers {TypeObjectUtils::build_common_struct_member(member_id_basic_layers, member_flags_basic_layers, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_basic_layers, common_basic_layers_ec))};
            if (!common_basic_layers_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure basic_layers member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_basic_layers = "basic_layers";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_basic_layers;
            ann_custom_ElevMapData.reset();
            CompleteMemberDetail detail_basic_layers = TypeObjectUtils::build_complete_member_detail(name_basic_layers, member_ann_builtin_basic_layers, ann_custom_ElevMapData);
            CompleteStructMember member_basic_layers = TypeObjectUtils::build_complete_struct_member(common_basic_layers, detail_basic_layers);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapData, member_basic_layers);
        }
        CompleteStructType struct_type_ElevMapData = TypeObjectUtils::build_complete_struct_type(struct_flags_ElevMapData, header_ElevMapData, member_seq_ElevMapData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ElevMapData, type_name_ElevMapData.to_string(), type_ids_ElevMapData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "elevmap_topic_base::ElevMapData already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace elevmap_topic_base

