// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file elevmap_topic_baseCdrAux.hpp
 * This source file contains some definitions of CDR related functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__ELEVMAP_TOPIC_BASE_ELEVMAP_TOPIC_BASECDRAUX_HPP
#define FAST_DDS_GENERATED__ELEVMAP_TOPIC_BASE_ELEVMAP_TOPIC_BASECDRAUX_HPP

#include "elevmap_topic_base.hpp"
constexpr uint32_t elevmap_topic_base_LayerData_max_cdr_typesize {160048UL};
constexpr uint32_t elevmap_topic_base_LayerData_max_key_cdr_typesize {0UL};

constexpr uint32_t elevmap_topic_base_ElevMapData_max_cdr_typesize {640541UL};
constexpr uint32_t elevmap_topic_base_ElevMapData_max_key_cdr_typesize {0UL};


namespace eprosima {
namespace fastcdr {

class Cdr;
class CdrSizeCalculator;

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const elevmap_topic_base::LayerData& data);

eProsima_user_DllExport void serialize_key(
        eprosima::fastcdr::Cdr& scdr,
        const elevmap_topic_base::ElevMapData& data);


} // namespace fastcdr
} // namespace eprosima

#endif // FAST_DDS_GENERATED__ELEVMAP_TOPIC_BASE_ELEVMAP_TOPIC_BASECDRAUX_HPP

