// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file elevmap_topic_base.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__ELEVMAP_TOPIC_BASE_ELEVMAP_TOPIC_BASE_HPP
#define FAST_DDS_GENERATED__ELEVMAP_TOPIC_BASE_ELEVMAP_TOPIC_BASE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ELEVMAP_TOPIC_BASE_SOURCE)
#define ELEVMAP_TOPIC_BASE_DllAPI __declspec( dllexport )
#else
#define ELEVMAP_TOPIC_BASE_DllAPI __declspec( dllimport )
#endif // ELEVMAP_TOPIC_BASE_SOURCE
#else
#define ELEVMAP_TOPIC_BASE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ELEVMAP_TOPIC_BASE_DllAPI
#endif // _WIN32

namespace elevmap_topic_base {

const uint32_t MAX_FRAME_ID_LEN = 128;
const uint32_t MAX_LAYER_NAME_LEN = 32;
const uint32_t MAX_CELLS = 40000;
const uint32_t MAX_LAYERS = 4;
/*!
 * @brief This class represents the structure LayerData defined by the user in the IDL file.
 * @ingroup elevmap_topic_base
 */
class LayerData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport LayerData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~LayerData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object LayerData that will be copied.
     */
    eProsima_user_DllExport LayerData(
            const LayerData& x)
    {
                    m_name = x.m_name;

                    m_data = x.m_data;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object LayerData that will be copied.
     */
    eProsima_user_DllExport LayerData(
            LayerData&& x) noexcept
    {
        m_name = std::move(x.m_name);
        m_data = std::move(x.m_data);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object LayerData that will be copied.
     */
    eProsima_user_DllExport LayerData& operator =(
            const LayerData& x)
    {

                    m_name = x.m_name;

                    m_data = x.m_data;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object LayerData that will be copied.
     */
    eProsima_user_DllExport LayerData& operator =(
            LayerData&& x) noexcept
    {

        m_name = std::move(x.m_name);
        m_data = std::move(x.m_data);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x LayerData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const LayerData& x) const
    {
        return (m_name == x.m_name &&
           m_data == x.m_data);
    }

    /*!
     * @brief Comparison operator.
     * @param x LayerData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const LayerData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member name
     * @param _name New value to be copied in member name
     */
    eProsima_user_DllExport void name(
            const eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>& _name)
    {
        m_name = _name;
    }

    /*!
     * @brief This function moves the value in member name
     * @param _name New value to be moved in member name
     */
    eProsima_user_DllExport void name(
            eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>&& _name)
    {
        m_name = std::move(_name);
    }

    /*!
     * @brief This function returns a constant reference to member name
     * @return Constant reference to member name
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>& name() const
    {
        return m_name;
    }

    /*!
     * @brief This function returns a reference to member name
     * @return Reference to member name
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>& name()
    {
        return m_name;
    }


    /*!
     * @brief This function copies the value in member data
     * @param _data New value to be copied in member data
     */
    eProsima_user_DllExport void data(
            const std::vector<float>& _data)
    {
        m_data = _data;
    }

    /*!
     * @brief This function moves the value in member data
     * @param _data New value to be moved in member data
     */
    eProsima_user_DllExport void data(
            std::vector<float>&& _data)
    {
        m_data = std::move(_data);
    }

    /*!
     * @brief This function returns a constant reference to member data
     * @return Constant reference to member data
     */
    eProsima_user_DllExport const std::vector<float>& data() const
    {
        return m_data;
    }

    /*!
     * @brief This function returns a reference to member data
     * @return Reference to member data
     */
    eProsima_user_DllExport std::vector<float>& data()
    {
        return m_data;
    }



private:

    eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN> m_name;
    std::vector<float> m_data;

};
/*!
 * @brief This class represents the structure ElevMapData defined by the user in the IDL file.
 * @ingroup elevmap_topic_base
 */
class ElevMapData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ElevMapData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ElevMapData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ElevMapData that will be copied.
     */
    eProsima_user_DllExport ElevMapData(
            const ElevMapData& x)
    {
                    m_frame_id = x.m_frame_id;

                    m_timestamp = x.m_timestamp;

                    m_resolution = x.m_resolution;

                    m_length_x = x.m_length_x;

                    m_length_y = x.m_length_y;

                    m_rows = x.m_rows;

                    m_cols = x.m_cols;

                    m_layers = x.m_layers;

                    m_basic_layers = x.m_basic_layers;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ElevMapData that will be copied.
     */
    eProsima_user_DllExport ElevMapData(
            ElevMapData&& x) noexcept
    {
        m_frame_id = std::move(x.m_frame_id);
        m_timestamp = x.m_timestamp;
        m_resolution = x.m_resolution;
        m_length_x = x.m_length_x;
        m_length_y = x.m_length_y;
        m_rows = x.m_rows;
        m_cols = x.m_cols;
        m_layers = std::move(x.m_layers);
        m_basic_layers = std::move(x.m_basic_layers);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ElevMapData that will be copied.
     */
    eProsima_user_DllExport ElevMapData& operator =(
            const ElevMapData& x)
    {

                    m_frame_id = x.m_frame_id;

                    m_timestamp = x.m_timestamp;

                    m_resolution = x.m_resolution;

                    m_length_x = x.m_length_x;

                    m_length_y = x.m_length_y;

                    m_rows = x.m_rows;

                    m_cols = x.m_cols;

                    m_layers = x.m_layers;

                    m_basic_layers = x.m_basic_layers;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ElevMapData that will be copied.
     */
    eProsima_user_DllExport ElevMapData& operator =(
            ElevMapData&& x) noexcept
    {

        m_frame_id = std::move(x.m_frame_id);
        m_timestamp = x.m_timestamp;
        m_resolution = x.m_resolution;
        m_length_x = x.m_length_x;
        m_length_y = x.m_length_y;
        m_rows = x.m_rows;
        m_cols = x.m_cols;
        m_layers = std::move(x.m_layers);
        m_basic_layers = std::move(x.m_basic_layers);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ElevMapData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ElevMapData& x) const
    {
        return (m_frame_id == x.m_frame_id &&
           m_timestamp == x.m_timestamp &&
           m_resolution == x.m_resolution &&
           m_length_x == x.m_length_x &&
           m_length_y == x.m_length_y &&
           m_rows == x.m_rows &&
           m_cols == x.m_cols &&
           m_layers == x.m_layers &&
           m_basic_layers == x.m_basic_layers);
    }

    /*!
     * @brief Comparison operator.
     * @param x ElevMapData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ElevMapData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& _frame_id)
    {
        m_frame_id = _frame_id;
    }

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>&& _frame_id)
    {
        m_frame_id = std::move(_frame_id);
    }

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& frame_id() const
    {
        return m_frame_id;
    }

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& frame_id()
    {
        return m_frame_id;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function sets a value in member resolution
     * @param _resolution New value for member resolution
     */
    eProsima_user_DllExport void resolution(
            double _resolution)
    {
        m_resolution = _resolution;
    }

    /*!
     * @brief This function returns the value of member resolution
     * @return Value of member resolution
     */
    eProsima_user_DllExport double resolution() const
    {
        return m_resolution;
    }

    /*!
     * @brief This function returns a reference to member resolution
     * @return Reference to member resolution
     */
    eProsima_user_DllExport double& resolution()
    {
        return m_resolution;
    }


    /*!
     * @brief This function sets a value in member length_x
     * @param _length_x New value for member length_x
     */
    eProsima_user_DllExport void length_x(
            double _length_x)
    {
        m_length_x = _length_x;
    }

    /*!
     * @brief This function returns the value of member length_x
     * @return Value of member length_x
     */
    eProsima_user_DllExport double length_x() const
    {
        return m_length_x;
    }

    /*!
     * @brief This function returns a reference to member length_x
     * @return Reference to member length_x
     */
    eProsima_user_DllExport double& length_x()
    {
        return m_length_x;
    }


    /*!
     * @brief This function sets a value in member length_y
     * @param _length_y New value for member length_y
     */
    eProsima_user_DllExport void length_y(
            double _length_y)
    {
        m_length_y = _length_y;
    }

    /*!
     * @brief This function returns the value of member length_y
     * @return Value of member length_y
     */
    eProsima_user_DllExport double length_y() const
    {
        return m_length_y;
    }

    /*!
     * @brief This function returns a reference to member length_y
     * @return Reference to member length_y
     */
    eProsima_user_DllExport double& length_y()
    {
        return m_length_y;
    }


    /*!
     * @brief This function sets a value in member rows
     * @param _rows New value for member rows
     */
    eProsima_user_DllExport void rows(
            uint32_t _rows)
    {
        m_rows = _rows;
    }

    /*!
     * @brief This function returns the value of member rows
     * @return Value of member rows
     */
    eProsima_user_DllExport uint32_t rows() const
    {
        return m_rows;
    }

    /*!
     * @brief This function returns a reference to member rows
     * @return Reference to member rows
     */
    eProsima_user_DllExport uint32_t& rows()
    {
        return m_rows;
    }


    /*!
     * @brief This function sets a value in member cols
     * @param _cols New value for member cols
     */
    eProsima_user_DllExport void cols(
            uint32_t _cols)
    {
        m_cols = _cols;
    }

    /*!
     * @brief This function returns the value of member cols
     * @return Value of member cols
     */
    eProsima_user_DllExport uint32_t cols() const
    {
        return m_cols;
    }

    /*!
     * @brief This function returns a reference to member cols
     * @return Reference to member cols
     */
    eProsima_user_DllExport uint32_t& cols()
    {
        return m_cols;
    }


    /*!
     * @brief This function copies the value in member layers
     * @param _layers New value to be copied in member layers
     */
    eProsima_user_DllExport void layers(
            const std::vector<LayerData>& _layers)
    {
        m_layers = _layers;
    }

    /*!
     * @brief This function moves the value in member layers
     * @param _layers New value to be moved in member layers
     */
    eProsima_user_DllExport void layers(
            std::vector<LayerData>&& _layers)
    {
        m_layers = std::move(_layers);
    }

    /*!
     * @brief This function returns a constant reference to member layers
     * @return Constant reference to member layers
     */
    eProsima_user_DllExport const std::vector<LayerData>& layers() const
    {
        return m_layers;
    }

    /*!
     * @brief This function returns a reference to member layers
     * @return Reference to member layers
     */
    eProsima_user_DllExport std::vector<LayerData>& layers()
    {
        return m_layers;
    }


    /*!
     * @brief This function copies the value in member basic_layers
     * @param _basic_layers New value to be copied in member basic_layers
     */
    eProsima_user_DllExport void basic_layers(
            const std::vector<eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>>& _basic_layers)
    {
        m_basic_layers = _basic_layers;
    }

    /*!
     * @brief This function moves the value in member basic_layers
     * @param _basic_layers New value to be moved in member basic_layers
     */
    eProsima_user_DllExport void basic_layers(
            std::vector<eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>>&& _basic_layers)
    {
        m_basic_layers = std::move(_basic_layers);
    }

    /*!
     * @brief This function returns a constant reference to member basic_layers
     * @return Constant reference to member basic_layers
     */
    eProsima_user_DllExport const std::vector<eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>>& basic_layers() const
    {
        return m_basic_layers;
    }

    /*!
     * @brief This function returns a reference to member basic_layers
     * @return Reference to member basic_layers
     */
    eProsima_user_DllExport std::vector<eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>>& basic_layers()
    {
        return m_basic_layers;
    }



private:

    eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN> m_frame_id;
    uint64_t m_timestamp{0};
    double m_resolution{0.0};
    double m_length_x{0.0};
    double m_length_y{0.0};
    uint32_t m_rows{0};
    uint32_t m_cols{0};
    std::vector<LayerData> m_layers;
    std::vector<eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>> m_basic_layers;

};

} // namespace elevmap_topic_base

#endif // _FAST_DDS_GENERATED_ELEVMAP_TOPIC_BASE_ELEVMAP_TOPIC_BASE_HPP_


