// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file elevmap_point_topic_baseTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "elevmap_point_topic_baseTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "elevmap_point_topic_base.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace elevmap_point_topic_base {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_PointXYZ_type_identifier(
        TypeIdentifierPair& type_ids_PointXYZ)
{

    ReturnCode_t return_code_PointXYZ {eprosima::fastdds::dds::RETCODE_OK};
    return_code_PointXYZ =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "elevmap_point_topic_base::PointXYZ", type_ids_PointXYZ);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_PointXYZ)
    {
        StructTypeFlag struct_flags_PointXYZ = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_PointXYZ = "elevmap_point_topic_base::PointXYZ";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_PointXYZ;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_PointXYZ;
        CompleteTypeDetail detail_PointXYZ = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_PointXYZ, ann_custom_PointXYZ, type_name_PointXYZ.to_string());
        CompleteStructHeader header_PointXYZ;
        header_PointXYZ = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_PointXYZ);
        CompleteStructMemberSeq member_seq_PointXYZ;
        {
            TypeIdentifierPair type_ids_x;
            ReturnCode_t return_code_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_x = 0x00000000;
            bool common_x_ec {false};
            CommonStructMember common_x {TypeObjectUtils::build_common_struct_member(member_id_x, member_flags_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_x, common_x_ec))};
            if (!common_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_x = "x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_x;
            ann_custom_PointXYZ.reset();
            CompleteMemberDetail detail_x = TypeObjectUtils::build_complete_member_detail(name_x, member_ann_builtin_x, ann_custom_PointXYZ);
            CompleteStructMember member_x = TypeObjectUtils::build_complete_struct_member(common_x, detail_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_PointXYZ, member_x);
        }
        {
            TypeIdentifierPair type_ids_y;
            ReturnCode_t return_code_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_y = 0x00000001;
            bool common_y_ec {false};
            CommonStructMember common_y {TypeObjectUtils::build_common_struct_member(member_id_y, member_flags_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_y, common_y_ec))};
            if (!common_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_y = "y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_y;
            ann_custom_PointXYZ.reset();
            CompleteMemberDetail detail_y = TypeObjectUtils::build_complete_member_detail(name_y, member_ann_builtin_y, ann_custom_PointXYZ);
            CompleteStructMember member_y = TypeObjectUtils::build_complete_struct_member(common_y, detail_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_PointXYZ, member_y);
        }
        {
            TypeIdentifierPair type_ids_z;
            ReturnCode_t return_code_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_float", type_ids_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_z = 0x00000002;
            bool common_z_ec {false};
            CommonStructMember common_z {TypeObjectUtils::build_common_struct_member(member_id_z, member_flags_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_z, common_z_ec))};
            if (!common_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_z = "z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_z;
            ann_custom_PointXYZ.reset();
            CompleteMemberDetail detail_z = TypeObjectUtils::build_complete_member_detail(name_z, member_ann_builtin_z, ann_custom_PointXYZ);
            CompleteStructMember member_z = TypeObjectUtils::build_complete_struct_member(common_z, detail_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_PointXYZ, member_z);
        }
        CompleteStructType struct_type_PointXYZ = TypeObjectUtils::build_complete_struct_type(struct_flags_PointXYZ, header_PointXYZ, member_seq_PointXYZ);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_PointXYZ, type_name_PointXYZ.to_string(), type_ids_PointXYZ))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "elevmap_point_topic_base::PointXYZ already registered in TypeObjectRegistry for a different type.");
        }
    }
}// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_ElevMapBodyPointCloud_type_identifier(
        TypeIdentifierPair& type_ids_ElevMapBodyPointCloud)
{

    ReturnCode_t return_code_ElevMapBodyPointCloud {eprosima::fastdds::dds::RETCODE_OK};
    return_code_ElevMapBodyPointCloud =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "elevmap_point_topic_base::ElevMapBodyPointCloud", type_ids_ElevMapBodyPointCloud);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_ElevMapBodyPointCloud)
    {
        StructTypeFlag struct_flags_ElevMapBodyPointCloud = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_ElevMapBodyPointCloud = "elevmap_point_topic_base::ElevMapBodyPointCloud";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_ElevMapBodyPointCloud;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_ElevMapBodyPointCloud;
        AppliedAnnotationSeq tmp_ann_custom_ElevMapBodyPointCloud;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_ElevMapBodyPointCloud;
        if (!tmp_ann_custom_ElevMapBodyPointCloud.empty())
        {
            ann_custom_ElevMapBodyPointCloud = tmp_ann_custom_ElevMapBodyPointCloud;
        }

        CompleteTypeDetail detail_ElevMapBodyPointCloud = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_ElevMapBodyPointCloud, ann_custom_ElevMapBodyPointCloud, type_name_ElevMapBodyPointCloud.to_string());
        CompleteStructHeader header_ElevMapBodyPointCloud;
        header_ElevMapBodyPointCloud = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_ElevMapBodyPointCloud);
        CompleteStructMemberSeq member_seq_ElevMapBodyPointCloud;
        {
            TypeIdentifierPair type_ids_frame_id;
            ReturnCode_t return_code_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_128", type_ids_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_id)
            {
                {
                    SBound bound = static_cast<SBound>(128);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_128", type_ids_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_128 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_id = 0x00000000;
            bool common_frame_id_ec {false};
            CommonStructMember common_frame_id {TypeObjectUtils::build_common_struct_member(member_id_frame_id, member_flags_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_id, common_frame_id_ec))};
            if (!common_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_id = "frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_id;
            ann_custom_ElevMapBodyPointCloud.reset();
            CompleteMemberDetail detail_frame_id = TypeObjectUtils::build_complete_member_detail(name_frame_id, member_ann_builtin_frame_id, ann_custom_ElevMapBodyPointCloud);
            CompleteStructMember member_frame_id = TypeObjectUtils::build_complete_struct_member(common_frame_id, detail_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapBodyPointCloud, member_frame_id);
        }
        {
            TypeIdentifierPair type_ids_timestamp_ns;
            ReturnCode_t return_code_timestamp_ns {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp_ns =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_timestamp_ns);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp_ns)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp_ns Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp_ns = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp_ns = 0x00000001;
            bool common_timestamp_ns_ec {false};
            CommonStructMember common_timestamp_ns {TypeObjectUtils::build_common_struct_member(member_id_timestamp_ns, member_flags_timestamp_ns, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp_ns, common_timestamp_ns_ec))};
            if (!common_timestamp_ns_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp_ns member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp_ns = "timestamp_ns";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp_ns;
            ann_custom_ElevMapBodyPointCloud.reset();
            CompleteMemberDetail detail_timestamp_ns = TypeObjectUtils::build_complete_member_detail(name_timestamp_ns, member_ann_builtin_timestamp_ns, ann_custom_ElevMapBodyPointCloud);
            CompleteStructMember member_timestamp_ns = TypeObjectUtils::build_complete_struct_member(common_timestamp_ns, detail_timestamp_ns);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapBodyPointCloud, member_timestamp_ns);
        }
        {
            TypeIdentifierPair type_ids_is_dense;
            ReturnCode_t return_code_is_dense {eprosima::fastdds::dds::RETCODE_OK};
            return_code_is_dense =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_bool", type_ids_is_dense);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_is_dense)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "is_dense Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_is_dense = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_is_dense = 0x00000002;
            bool common_is_dense_ec {false};
            CommonStructMember common_is_dense {TypeObjectUtils::build_common_struct_member(member_id_is_dense, member_flags_is_dense, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_is_dense, common_is_dense_ec))};
            if (!common_is_dense_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure is_dense member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_is_dense = "is_dense";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_is_dense;
            ann_custom_ElevMapBodyPointCloud.reset();
            CompleteMemberDetail detail_is_dense = TypeObjectUtils::build_complete_member_detail(name_is_dense, member_ann_builtin_is_dense, ann_custom_ElevMapBodyPointCloud);
            CompleteStructMember member_is_dense = TypeObjectUtils::build_complete_struct_member(common_is_dense, detail_is_dense);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapBodyPointCloud, member_is_dense);
        }
        {
            TypeIdentifierPair type_ids_layer_name;
            ReturnCode_t return_code_layer_name {eprosima::fastdds::dds::RETCODE_OK};
            return_code_layer_name =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_32", type_ids_layer_name);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_layer_name)
            {
                {
                    SBound bound = static_cast<SBound>(32);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_32", type_ids_layer_name))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_32 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_layer_name = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_layer_name = 0x00000003;
            bool common_layer_name_ec {false};
            CommonStructMember common_layer_name {TypeObjectUtils::build_common_struct_member(member_id_layer_name, member_flags_layer_name, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_layer_name, common_layer_name_ec))};
            if (!common_layer_name_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure layer_name member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_layer_name = "layer_name";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_layer_name;
            ann_custom_ElevMapBodyPointCloud.reset();
            CompleteMemberDetail detail_layer_name = TypeObjectUtils::build_complete_member_detail(name_layer_name, member_ann_builtin_layer_name, ann_custom_ElevMapBodyPointCloud);
            CompleteStructMember member_layer_name = TypeObjectUtils::build_complete_struct_member(common_layer_name, detail_layer_name);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapBodyPointCloud, member_layer_name);
        }
        {
            TypeIdentifierPair type_ids_points;
            ReturnCode_t return_code_points {eprosima::fastdds::dds::RETCODE_OK};
            return_code_points =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072", type_ids_points);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_points)
            {
                return_code_points =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "elevmap_point_topic_base::PointXYZ", type_ids_points);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_points)
                {
                    ::elevmap_point_topic_base::register_PointXYZ_type_identifier(type_ids_points);
                }
                bool element_identifier_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_points, element_identifier_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072_ec))};
                if (!element_identifier_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072 = EK_COMPLETE;
                if (TK_NONE == type_ids_points.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072 = 0;
                PlainCollectionHeader header_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072, element_flags_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072);
                {
                    LBound bound = 131072;
                    PlainSequenceLElemDefn seq_ldefn = TypeObjectUtils::build_plain_sequence_l_elem_defn(header_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_l_sequence_type_identifier(seq_ldefn, "anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072", type_ids_points))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_elevmap_point_topic_base_PointXYZ_131072 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_points = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_points = 0x00000004;
            bool common_points_ec {false};
            CommonStructMember common_points {TypeObjectUtils::build_common_struct_member(member_id_points, member_flags_points, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_points, common_points_ec))};
            if (!common_points_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure points member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_points = "points";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_points;
            ann_custom_ElevMapBodyPointCloud.reset();
            CompleteMemberDetail detail_points = TypeObjectUtils::build_complete_member_detail(name_points, member_ann_builtin_points, ann_custom_ElevMapBodyPointCloud);
            CompleteStructMember member_points = TypeObjectUtils::build_complete_struct_member(common_points, detail_points);
            TypeObjectUtils::add_complete_struct_member(member_seq_ElevMapBodyPointCloud, member_points);
        }
        CompleteStructType struct_type_ElevMapBodyPointCloud = TypeObjectUtils::build_complete_struct_type(struct_flags_ElevMapBodyPointCloud, header_ElevMapBodyPointCloud, member_seq_ElevMapBodyPointCloud);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_ElevMapBodyPointCloud, type_name_ElevMapBodyPointCloud.to_string(), type_ids_ElevMapBodyPointCloud))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "elevmap_point_topic_base::ElevMapBodyPointCloud already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace elevmap_point_topic_base

