// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file elevmap_point_topic_base.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__ELEVMAP_POINT_TOPIC_BASE_ELEVMAP_POINT_TOPIC_BASE_HPP
#define FAST_DDS_GENERATED__ELEVMAP_POINT_TOPIC_BASE_ELEVMAP_POINT_TOPIC_BASE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ELEVMAP_POINT_TOPIC_BASE_SOURCE)
#define ELEVMAP_POINT_TOPIC_BASE_DllAPI __declspec( dllexport )
#else
#define ELEVMAP_POINT_TOPIC_BASE_DllAPI __declspec( dllimport )
#endif // ELEVMAP_POINT_TOPIC_BASE_SOURCE
#else
#define ELEVMAP_POINT_TOPIC_BASE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ELEVMAP_POINT_TOPIC_BASE_DllAPI
#endif // _WIN32

namespace elevmap_point_topic_base {

const uint32_t MAX_FRAME_ID_LEN = 128;
const uint32_t MAX_LAYER_NAME_LEN = 32;
const uint32_t MAX_POINTS = 131072;
/*!
 * @brief This class represents the structure PointXYZ defined by the user in the IDL file.
 * @ingroup elevmap_point_topic_base
 */
class PointXYZ
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport PointXYZ()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~PointXYZ()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object PointXYZ that will be copied.
     */
    eProsima_user_DllExport PointXYZ(
            const PointXYZ& x)
    {
                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object PointXYZ that will be copied.
     */
    eProsima_user_DllExport PointXYZ(
            PointXYZ&& x) noexcept
    {
        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object PointXYZ that will be copied.
     */
    eProsima_user_DllExport PointXYZ& operator =(
            const PointXYZ& x)
    {

                    m_x = x.m_x;

                    m_y = x.m_y;

                    m_z = x.m_z;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object PointXYZ that will be copied.
     */
    eProsima_user_DllExport PointXYZ& operator =(
            PointXYZ&& x) noexcept
    {

        m_x = x.m_x;
        m_y = x.m_y;
        m_z = x.m_z;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x PointXYZ object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const PointXYZ& x) const
    {
        return (m_x == x.m_x &&
           m_y == x.m_y &&
           m_z == x.m_z);
    }

    /*!
     * @brief Comparison operator.
     * @param x PointXYZ object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const PointXYZ& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member x
     * @param _x New value for member x
     */
    eProsima_user_DllExport void x(
            float _x)
    {
        m_x = _x;
    }

    /*!
     * @brief This function returns the value of member x
     * @return Value of member x
     */
    eProsima_user_DllExport float x() const
    {
        return m_x;
    }

    /*!
     * @brief This function returns a reference to member x
     * @return Reference to member x
     */
    eProsima_user_DllExport float& x()
    {
        return m_x;
    }


    /*!
     * @brief This function sets a value in member y
     * @param _y New value for member y
     */
    eProsima_user_DllExport void y(
            float _y)
    {
        m_y = _y;
    }

    /*!
     * @brief This function returns the value of member y
     * @return Value of member y
     */
    eProsima_user_DllExport float y() const
    {
        return m_y;
    }

    /*!
     * @brief This function returns a reference to member y
     * @return Reference to member y
     */
    eProsima_user_DllExport float& y()
    {
        return m_y;
    }


    /*!
     * @brief This function sets a value in member z
     * @param _z New value for member z
     */
    eProsima_user_DllExport void z(
            float _z)
    {
        m_z = _z;
    }

    /*!
     * @brief This function returns the value of member z
     * @return Value of member z
     */
    eProsima_user_DllExport float z() const
    {
        return m_z;
    }

    /*!
     * @brief This function returns a reference to member z
     * @return Reference to member z
     */
    eProsima_user_DllExport float& z()
    {
        return m_z;
    }



private:

    float m_x{0.0};
    float m_y{0.0};
    float m_z{0.0};

};
/*!
 * @brief This class represents the structure ElevMapBodyPointCloud defined by the user in the IDL file.
 * @ingroup elevmap_point_topic_base
 */
class ElevMapBodyPointCloud
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport ElevMapBodyPointCloud()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~ElevMapBodyPointCloud()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object ElevMapBodyPointCloud that will be copied.
     */
    eProsima_user_DllExport ElevMapBodyPointCloud(
            const ElevMapBodyPointCloud& x)
    {
                    m_frame_id = x.m_frame_id;

                    m_timestamp_ns = x.m_timestamp_ns;

                    m_is_dense = x.m_is_dense;

                    m_layer_name = x.m_layer_name;

                    m_points = x.m_points;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object ElevMapBodyPointCloud that will be copied.
     */
    eProsima_user_DllExport ElevMapBodyPointCloud(
            ElevMapBodyPointCloud&& x) noexcept
    {
        m_frame_id = std::move(x.m_frame_id);
        m_timestamp_ns = x.m_timestamp_ns;
        m_is_dense = x.m_is_dense;
        m_layer_name = std::move(x.m_layer_name);
        m_points = std::move(x.m_points);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object ElevMapBodyPointCloud that will be copied.
     */
    eProsima_user_DllExport ElevMapBodyPointCloud& operator =(
            const ElevMapBodyPointCloud& x)
    {

                    m_frame_id = x.m_frame_id;

                    m_timestamp_ns = x.m_timestamp_ns;

                    m_is_dense = x.m_is_dense;

                    m_layer_name = x.m_layer_name;

                    m_points = x.m_points;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object ElevMapBodyPointCloud that will be copied.
     */
    eProsima_user_DllExport ElevMapBodyPointCloud& operator =(
            ElevMapBodyPointCloud&& x) noexcept
    {

        m_frame_id = std::move(x.m_frame_id);
        m_timestamp_ns = x.m_timestamp_ns;
        m_is_dense = x.m_is_dense;
        m_layer_name = std::move(x.m_layer_name);
        m_points = std::move(x.m_points);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x ElevMapBodyPointCloud object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const ElevMapBodyPointCloud& x) const
    {
        return (m_frame_id == x.m_frame_id &&
           m_timestamp_ns == x.m_timestamp_ns &&
           m_is_dense == x.m_is_dense &&
           m_layer_name == x.m_layer_name &&
           m_points == x.m_points);
    }

    /*!
     * @brief Comparison operator.
     * @param x ElevMapBodyPointCloud object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const ElevMapBodyPointCloud& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& _frame_id)
    {
        m_frame_id = _frame_id;
    }

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>&& _frame_id)
    {
        m_frame_id = std::move(_frame_id);
    }

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& frame_id() const
    {
        return m_frame_id;
    }

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& frame_id()
    {
        return m_frame_id;
    }


    /*!
     * @brief This function sets a value in member timestamp_ns
     * @param _timestamp_ns New value for member timestamp_ns
     */
    eProsima_user_DllExport void timestamp_ns(
            uint64_t _timestamp_ns)
    {
        m_timestamp_ns = _timestamp_ns;
    }

    /*!
     * @brief This function returns the value of member timestamp_ns
     * @return Value of member timestamp_ns
     */
    eProsima_user_DllExport uint64_t timestamp_ns() const
    {
        return m_timestamp_ns;
    }

    /*!
     * @brief This function returns a reference to member timestamp_ns
     * @return Reference to member timestamp_ns
     */
    eProsima_user_DllExport uint64_t& timestamp_ns()
    {
        return m_timestamp_ns;
    }


    /*!
     * @brief This function sets a value in member is_dense
     * @param _is_dense New value for member is_dense
     */
    eProsima_user_DllExport void is_dense(
            bool _is_dense)
    {
        m_is_dense = _is_dense;
    }

    /*!
     * @brief This function returns the value of member is_dense
     * @return Value of member is_dense
     */
    eProsima_user_DllExport bool is_dense() const
    {
        return m_is_dense;
    }

    /*!
     * @brief This function returns a reference to member is_dense
     * @return Reference to member is_dense
     */
    eProsima_user_DllExport bool& is_dense()
    {
        return m_is_dense;
    }


    /*!
     * @brief This function copies the value in member layer_name
     * @param _layer_name New value to be copied in member layer_name
     */
    eProsima_user_DllExport void layer_name(
            const eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>& _layer_name)
    {
        m_layer_name = _layer_name;
    }

    /*!
     * @brief This function moves the value in member layer_name
     * @param _layer_name New value to be moved in member layer_name
     */
    eProsima_user_DllExport void layer_name(
            eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>&& _layer_name)
    {
        m_layer_name = std::move(_layer_name);
    }

    /*!
     * @brief This function returns a constant reference to member layer_name
     * @return Constant reference to member layer_name
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>& layer_name() const
    {
        return m_layer_name;
    }

    /*!
     * @brief This function returns a reference to member layer_name
     * @return Reference to member layer_name
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN>& layer_name()
    {
        return m_layer_name;
    }


    /*!
     * @brief This function copies the value in member points
     * @param _points New value to be copied in member points
     */
    eProsima_user_DllExport void points(
            const std::vector<PointXYZ>& _points)
    {
        m_points = _points;
    }

    /*!
     * @brief This function moves the value in member points
     * @param _points New value to be moved in member points
     */
    eProsima_user_DllExport void points(
            std::vector<PointXYZ>&& _points)
    {
        m_points = std::move(_points);
    }

    /*!
     * @brief This function returns a constant reference to member points
     * @return Constant reference to member points
     */
    eProsima_user_DllExport const std::vector<PointXYZ>& points() const
    {
        return m_points;
    }

    /*!
     * @brief This function returns a reference to member points
     * @return Reference to member points
     */
    eProsima_user_DllExport std::vector<PointXYZ>& points()
    {
        return m_points;
    }



private:

    eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN> m_frame_id;
    uint64_t m_timestamp_ns{0};
    bool m_is_dense{false};
    eprosima::fastcdr::fixed_string<MAX_LAYER_NAME_LEN> m_layer_name;
    std::vector<PointXYZ> m_points;

};

} // namespace elevmap_point_topic_base

#endif // _FAST_DDS_GENERATED_ELEVMAP_POINT_TOPIC_BASE_ELEVMAP_POINT_TOPIC_BASE_HPP_


