// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file motor_command_12.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#ifndef FAST_DDS_GENERATED__MOTOR_COMMAND_12_MOTOR_COMMAND_12_HPP
#define FAST_DDS_GENERATED__MOTOR_COMMAND_12_MOTOR_COMMAND_12_HPP

#include <array>
#include <cstdint>
#include <utility>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MOTOR_COMMAND_12_SOURCE)
#define MOTOR_COMMAND_12_DllAPI __declspec( dllexport )
#else
#define MOTOR_COMMAND_12_DllAPI __declspec( dllimport )
#endif // MOTOR_COMMAND_12_SOURCE
#else
#define MOTOR_COMMAND_12_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define MOTOR_COMMAND_12_DllAPI
#endif // _WIN32

namespace Motor_Command_12 {

/*!
 * @brief This class represents the structure motor_cmd defined by the user in the IDL file.
 * @ingroup motor_command_12
 */
class motor_cmd
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport motor_cmd()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~motor_cmd()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object motor_cmd that will be copied.
     */
    eProsima_user_DllExport motor_cmd(
            const motor_cmd& x)
    {
                    m_kp = x.m_kp;

                    m_kd = x.m_kd;

                    m_pos = x.m_pos;

                    m_vel = x.m_vel;

                    m_torque = x.m_torque;

                    m_ff_torque = x.m_ff_torque;

                    m_mode = x.m_mode;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object motor_cmd that will be copied.
     */
    eProsima_user_DllExport motor_cmd(
            motor_cmd&& x) noexcept
    {
        m_kp = std::move(x.m_kp);
        m_kd = std::move(x.m_kd);
        m_pos = std::move(x.m_pos);
        m_vel = std::move(x.m_vel);
        m_torque = std::move(x.m_torque);
        m_ff_torque = std::move(x.m_ff_torque);
        m_mode = std::move(x.m_mode);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object motor_cmd that will be copied.
     */
    eProsima_user_DllExport motor_cmd& operator =(
            const motor_cmd& x)
    {

                    m_kp = x.m_kp;

                    m_kd = x.m_kd;

                    m_pos = x.m_pos;

                    m_vel = x.m_vel;

                    m_torque = x.m_torque;

                    m_ff_torque = x.m_ff_torque;

                    m_mode = x.m_mode;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object motor_cmd that will be copied.
     */
    eProsima_user_DllExport motor_cmd& operator =(
            motor_cmd&& x) noexcept
    {

        m_kp = std::move(x.m_kp);
        m_kd = std::move(x.m_kd);
        m_pos = std::move(x.m_pos);
        m_vel = std::move(x.m_vel);
        m_torque = std::move(x.m_torque);
        m_ff_torque = std::move(x.m_ff_torque);
        m_mode = std::move(x.m_mode);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x motor_cmd object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const motor_cmd& x) const
    {
        return (m_kp == x.m_kp &&
           m_kd == x.m_kd &&
           m_pos == x.m_pos &&
           m_vel == x.m_vel &&
           m_torque == x.m_torque &&
           m_ff_torque == x.m_ff_torque &&
           m_mode == x.m_mode);
    }

    /*!
     * @brief Comparison operator.
     * @param x motor_cmd object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const motor_cmd& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member kp
     * @param _kp New value to be copied in member kp
     */
    eProsima_user_DllExport void kp(
            const std::array<float, 12>& _kp)
    {
        m_kp = _kp;
    }

    /*!
     * @brief This function moves the value in member kp
     * @param _kp New value to be moved in member kp
     */
    eProsima_user_DllExport void kp(
            std::array<float, 12>&& _kp)
    {
        m_kp = std::move(_kp);
    }

    /*!
     * @brief This function returns a constant reference to member kp
     * @return Constant reference to member kp
     */
    eProsima_user_DllExport const std::array<float, 12>& kp() const
    {
        return m_kp;
    }

    /*!
     * @brief This function returns a reference to member kp
     * @return Reference to member kp
     */
    eProsima_user_DllExport std::array<float, 12>& kp()
    {
        return m_kp;
    }


    /*!
     * @brief This function copies the value in member kd
     * @param _kd New value to be copied in member kd
     */
    eProsima_user_DllExport void kd(
            const std::array<float, 12>& _kd)
    {
        m_kd = _kd;
    }

    /*!
     * @brief This function moves the value in member kd
     * @param _kd New value to be moved in member kd
     */
    eProsima_user_DllExport void kd(
            std::array<float, 12>&& _kd)
    {
        m_kd = std::move(_kd);
    }

    /*!
     * @brief This function returns a constant reference to member kd
     * @return Constant reference to member kd
     */
    eProsima_user_DllExport const std::array<float, 12>& kd() const
    {
        return m_kd;
    }

    /*!
     * @brief This function returns a reference to member kd
     * @return Reference to member kd
     */
    eProsima_user_DllExport std::array<float, 12>& kd()
    {
        return m_kd;
    }


    /*!
     * @brief This function copies the value in member pos
     * @param _pos New value to be copied in member pos
     */
    eProsima_user_DllExport void pos(
            const std::array<float, 12>& _pos)
    {
        m_pos = _pos;
    }

    /*!
     * @brief This function moves the value in member pos
     * @param _pos New value to be moved in member pos
     */
    eProsima_user_DllExport void pos(
            std::array<float, 12>&& _pos)
    {
        m_pos = std::move(_pos);
    }

    /*!
     * @brief This function returns a constant reference to member pos
     * @return Constant reference to member pos
     */
    eProsima_user_DllExport const std::array<float, 12>& pos() const
    {
        return m_pos;
    }

    /*!
     * @brief This function returns a reference to member pos
     * @return Reference to member pos
     */
    eProsima_user_DllExport std::array<float, 12>& pos()
    {
        return m_pos;
    }


    /*!
     * @brief This function copies the value in member vel
     * @param _vel New value to be copied in member vel
     */
    eProsima_user_DllExport void vel(
            const std::array<float, 12>& _vel)
    {
        m_vel = _vel;
    }

    /*!
     * @brief This function moves the value in member vel
     * @param _vel New value to be moved in member vel
     */
    eProsima_user_DllExport void vel(
            std::array<float, 12>&& _vel)
    {
        m_vel = std::move(_vel);
    }

    /*!
     * @brief This function returns a constant reference to member vel
     * @return Constant reference to member vel
     */
    eProsima_user_DllExport const std::array<float, 12>& vel() const
    {
        return m_vel;
    }

    /*!
     * @brief This function returns a reference to member vel
     * @return Reference to member vel
     */
    eProsima_user_DllExport std::array<float, 12>& vel()
    {
        return m_vel;
    }


    /*!
     * @brief This function copies the value in member torque
     * @param _torque New value to be copied in member torque
     */
    eProsima_user_DllExport void torque(
            const std::array<float, 12>& _torque)
    {
        m_torque = _torque;
    }

    /*!
     * @brief This function moves the value in member torque
     * @param _torque New value to be moved in member torque
     */
    eProsima_user_DllExport void torque(
            std::array<float, 12>&& _torque)
    {
        m_torque = std::move(_torque);
    }

    /*!
     * @brief This function returns a constant reference to member torque
     * @return Constant reference to member torque
     */
    eProsima_user_DllExport const std::array<float, 12>& torque() const
    {
        return m_torque;
    }

    /*!
     * @brief This function returns a reference to member torque
     * @return Reference to member torque
     */
    eProsima_user_DllExport std::array<float, 12>& torque()
    {
        return m_torque;
    }


    /*!
     * @brief This function copies the value in member ff_torque
     * @param _ff_torque New value to be copied in member ff_torque
     */
    eProsima_user_DllExport void ff_torque(
            const std::array<float, 12>& _ff_torque)
    {
        m_ff_torque = _ff_torque;
    }

    /*!
     * @brief This function moves the value in member ff_torque
     * @param _ff_torque New value to be moved in member ff_torque
     */
    eProsima_user_DllExport void ff_torque(
            std::array<float, 12>&& _ff_torque)
    {
        m_ff_torque = std::move(_ff_torque);
    }

    /*!
     * @brief This function returns a constant reference to member ff_torque
     * @return Constant reference to member ff_torque
     */
    eProsima_user_DllExport const std::array<float, 12>& ff_torque() const
    {
        return m_ff_torque;
    }

    /*!
     * @brief This function returns a reference to member ff_torque
     * @return Reference to member ff_torque
     */
    eProsima_user_DllExport std::array<float, 12>& ff_torque()
    {
        return m_ff_torque;
    }


    /*!
     * @brief This function copies the value in member mode
     * @param _mode New value to be copied in member mode
     */
    eProsima_user_DllExport void mode(
            const std::array<uint32_t, 12>& _mode)
    {
        m_mode = _mode;
    }

    /*!
     * @brief This function moves the value in member mode
     * @param _mode New value to be moved in member mode
     */
    eProsima_user_DllExport void mode(
            std::array<uint32_t, 12>&& _mode)
    {
        m_mode = std::move(_mode);
    }

    /*!
     * @brief This function returns a constant reference to member mode
     * @return Constant reference to member mode
     */
    eProsima_user_DllExport const std::array<uint32_t, 12>& mode() const
    {
        return m_mode;
    }

    /*!
     * @brief This function returns a reference to member mode
     * @return Reference to member mode
     */
    eProsima_user_DllExport std::array<uint32_t, 12>& mode()
    {
        return m_mode;
    }



private:

    std::array<float, 12> m_kp{0.0};
    std::array<float, 12> m_kd{0.0};
    std::array<float, 12> m_pos{0.0};
    std::array<float, 12> m_vel{0.0};
    std::array<float, 12> m_torque{0.0};
    std::array<float, 12> m_ff_torque{0.0};
    std::array<uint32_t, 12> m_mode{0};

};

} // namespace Motor_Command_12

#endif // _FAST_DDS_GENERATED_MOTOR_COMMAND_12_MOTOR_COMMAND_12_HPP_


