module Motor_Command_12
{
    @final  // 标记此类型为 Final，以优化序列化
    struct motor_cmd
    {
        float kp[12];                 // 位置环比例系数
        float kd[12];                 // 阻尼系数
        float pos[12];                // 目标位置
        float vel[12];                // 目标速度
        float torque[12];             // 目标力矩
        float ff_torque[12];             // 目标力矩
        uint32 mode[12];              // 控制模式
    };
};
