// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file odom_topic_baseTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#include "odom_topic_baseTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "odom_topic_base.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace odom_topic_base {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_OdomData_type_identifier(
        TypeIdentifierPair& type_ids_OdomData)
{

    ReturnCode_t return_code_OdomData {eprosima::fastdds::dds::RETCODE_OK};
    return_code_OdomData =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "odom_topic_base::OdomData", type_ids_OdomData);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_OdomData)
    {
        StructTypeFlag struct_flags_OdomData = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_OdomData = "odom_topic_base::OdomData";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_OdomData;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_OdomData;
        AppliedAnnotationSeq tmp_ann_custom_OdomData;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_OdomData;
        if (!tmp_ann_custom_OdomData.empty())
        {
            ann_custom_OdomData = tmp_ann_custom_OdomData;
        }

        CompleteTypeDetail detail_OdomData = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_OdomData, ann_custom_OdomData, type_name_OdomData.to_string());
        CompleteStructHeader header_OdomData;
        header_OdomData = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_OdomData);
        CompleteStructMemberSeq member_seq_OdomData;
        {
            TypeIdentifierPair type_ids_frame_id;
            ReturnCode_t return_code_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_128", type_ids_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_frame_id)
            {
                {
                    SBound bound = static_cast<SBound>(128);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_128", type_ids_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_128 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_frame_id = 0x00000000;
            bool common_frame_id_ec {false};
            CommonStructMember common_frame_id {TypeObjectUtils::build_common_struct_member(member_id_frame_id, member_flags_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_frame_id, common_frame_id_ec))};
            if (!common_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_frame_id = "frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_frame_id;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_frame_id = TypeObjectUtils::build_complete_member_detail(name_frame_id, member_ann_builtin_frame_id, ann_custom_OdomData);
            CompleteStructMember member_frame_id = TypeObjectUtils::build_complete_struct_member(common_frame_id, detail_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_frame_id);
        }
        {
            TypeIdentifierPair type_ids_child_frame_id;
            ReturnCode_t return_code_child_frame_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_child_frame_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_128", type_ids_child_frame_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_child_frame_id)
            {
                {
                    SBound bound = static_cast<SBound>(128);
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_128", type_ids_child_frame_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_128 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_child_frame_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_child_frame_id = 0x00000001;
            bool common_child_frame_id_ec {false};
            CommonStructMember common_child_frame_id {TypeObjectUtils::build_common_struct_member(member_id_child_frame_id, member_flags_child_frame_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_child_frame_id, common_child_frame_id_ec))};
            if (!common_child_frame_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure child_frame_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_child_frame_id = "child_frame_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_child_frame_id;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_child_frame_id = TypeObjectUtils::build_complete_member_detail(name_child_frame_id, member_ann_builtin_child_frame_id, ann_custom_OdomData);
            CompleteStructMember member_child_frame_id = TypeObjectUtils::build_complete_struct_member(common_child_frame_id, detail_child_frame_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_child_frame_id);
        }
        {
            TypeIdentifierPair type_ids_timestamp;
            ReturnCode_t return_code_timestamp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_timestamp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_uint64_t", type_ids_timestamp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_timestamp)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "timestamp Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_timestamp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_timestamp = 0x00000002;
            bool common_timestamp_ec {false};
            CommonStructMember common_timestamp {TypeObjectUtils::build_common_struct_member(member_id_timestamp, member_flags_timestamp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_timestamp, common_timestamp_ec))};
            if (!common_timestamp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure timestamp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_timestamp = "timestamp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_timestamp;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_timestamp = TypeObjectUtils::build_complete_member_detail(name_timestamp, member_ann_builtin_timestamp, ann_custom_OdomData);
            CompleteStructMember member_timestamp = TypeObjectUtils::build_complete_struct_member(common_timestamp, detail_timestamp);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_timestamp);
        }
        {
            TypeIdentifierPair type_ids_position_x;
            ReturnCode_t return_code_position_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_position_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "position_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_position_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position_x = 0x00000003;
            bool common_position_x_ec {false};
            CommonStructMember common_position_x {TypeObjectUtils::build_common_struct_member(member_id_position_x, member_flags_position_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_x, common_position_x_ec))};
            if (!common_position_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position_x = "position_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position_x;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_position_x = TypeObjectUtils::build_complete_member_detail(name_position_x, member_ann_builtin_position_x, ann_custom_OdomData);
            CompleteStructMember member_position_x = TypeObjectUtils::build_complete_struct_member(common_position_x, detail_position_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_position_x);
        }
        {
            TypeIdentifierPair type_ids_position_y;
            ReturnCode_t return_code_position_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_position_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "position_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_position_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position_y = 0x00000004;
            bool common_position_y_ec {false};
            CommonStructMember common_position_y {TypeObjectUtils::build_common_struct_member(member_id_position_y, member_flags_position_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_y, common_position_y_ec))};
            if (!common_position_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position_y = "position_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position_y;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_position_y = TypeObjectUtils::build_complete_member_detail(name_position_y, member_ann_builtin_position_y, ann_custom_OdomData);
            CompleteStructMember member_position_y = TypeObjectUtils::build_complete_struct_member(common_position_y, detail_position_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_position_y);
        }
        {
            TypeIdentifierPair type_ids_position_z;
            ReturnCode_t return_code_position_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_position_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_position_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_position_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "position_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_position_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_position_z = 0x00000005;
            bool common_position_z_ec {false};
            CommonStructMember common_position_z {TypeObjectUtils::build_common_struct_member(member_id_position_z, member_flags_position_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_position_z, common_position_z_ec))};
            if (!common_position_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure position_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_position_z = "position_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_position_z;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_position_z = TypeObjectUtils::build_complete_member_detail(name_position_z, member_ann_builtin_position_z, ann_custom_OdomData);
            CompleteStructMember member_position_z = TypeObjectUtils::build_complete_struct_member(common_position_z, detail_position_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_position_z);
        }
        {
            TypeIdentifierPair type_ids_orientation_x;
            ReturnCode_t return_code_orientation_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_x = 0x00000006;
            bool common_orientation_x_ec {false};
            CommonStructMember common_orientation_x {TypeObjectUtils::build_common_struct_member(member_id_orientation_x, member_flags_orientation_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_x, common_orientation_x_ec))};
            if (!common_orientation_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_x = "orientation_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_x;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_orientation_x = TypeObjectUtils::build_complete_member_detail(name_orientation_x, member_ann_builtin_orientation_x, ann_custom_OdomData);
            CompleteStructMember member_orientation_x = TypeObjectUtils::build_complete_struct_member(common_orientation_x, detail_orientation_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_orientation_x);
        }
        {
            TypeIdentifierPair type_ids_orientation_y;
            ReturnCode_t return_code_orientation_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_y = 0x00000007;
            bool common_orientation_y_ec {false};
            CommonStructMember common_orientation_y {TypeObjectUtils::build_common_struct_member(member_id_orientation_y, member_flags_orientation_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_y, common_orientation_y_ec))};
            if (!common_orientation_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_y = "orientation_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_y;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_orientation_y = TypeObjectUtils::build_complete_member_detail(name_orientation_y, member_ann_builtin_orientation_y, ann_custom_OdomData);
            CompleteStructMember member_orientation_y = TypeObjectUtils::build_complete_struct_member(common_orientation_y, detail_orientation_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_orientation_y);
        }
        {
            TypeIdentifierPair type_ids_orientation_z;
            ReturnCode_t return_code_orientation_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_z = 0x00000008;
            bool common_orientation_z_ec {false};
            CommonStructMember common_orientation_z {TypeObjectUtils::build_common_struct_member(member_id_orientation_z, member_flags_orientation_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_z, common_orientation_z_ec))};
            if (!common_orientation_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_z = "orientation_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_z;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_orientation_z = TypeObjectUtils::build_complete_member_detail(name_orientation_z, member_ann_builtin_orientation_z, ann_custom_OdomData);
            CompleteStructMember member_orientation_z = TypeObjectUtils::build_complete_struct_member(common_orientation_z, detail_orientation_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_orientation_z);
        }
        {
            TypeIdentifierPair type_ids_orientation_w;
            ReturnCode_t return_code_orientation_w {eprosima::fastdds::dds::RETCODE_OK};
            return_code_orientation_w =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_orientation_w);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_orientation_w)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "orientation_w Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_orientation_w = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_orientation_w = 0x00000009;
            bool common_orientation_w_ec {false};
            CommonStructMember common_orientation_w {TypeObjectUtils::build_common_struct_member(member_id_orientation_w, member_flags_orientation_w, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_orientation_w, common_orientation_w_ec))};
            if (!common_orientation_w_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure orientation_w member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_orientation_w = "orientation_w";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_orientation_w;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_orientation_w = TypeObjectUtils::build_complete_member_detail(name_orientation_w, member_ann_builtin_orientation_w, ann_custom_OdomData);
            CompleteStructMember member_orientation_w = TypeObjectUtils::build_complete_struct_member(common_orientation_w, detail_orientation_w);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_orientation_w);
        }
        {
            TypeIdentifierPair type_ids_pose_covariance;
            ReturnCode_t return_code_pose_covariance {eprosima::fastdds::dds::RETCODE_OK};
            return_code_pose_covariance =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_double_36", type_ids_pose_covariance);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_pose_covariance)
            {
                return_code_pose_covariance =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_pose_covariance);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_pose_covariance)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_sequence_double_36_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_double_36 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pose_covariance, element_identifier_anonymous_sequence_double_36_ec))};
                if (!element_identifier_anonymous_sequence_double_36_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_double_36 = EK_COMPLETE;
                if (TK_NONE == type_ids_pose_covariance.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_double_36 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_double_36 = 0;
                PlainCollectionHeader header_anonymous_sequence_double_36 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_double_36, element_flags_anonymous_sequence_double_36);
                {
                    SBound bound = static_cast<SBound>(36);
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_double_36, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_double_36));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_double_36", type_ids_pose_covariance))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_double_36 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_pose_covariance = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_pose_covariance = 0x0000000a;
            bool common_pose_covariance_ec {false};
            CommonStructMember common_pose_covariance {TypeObjectUtils::build_common_struct_member(member_id_pose_covariance, member_flags_pose_covariance, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pose_covariance, common_pose_covariance_ec))};
            if (!common_pose_covariance_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure pose_covariance member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_pose_covariance = "pose_covariance";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_pose_covariance;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_pose_covariance = TypeObjectUtils::build_complete_member_detail(name_pose_covariance, member_ann_builtin_pose_covariance, ann_custom_OdomData);
            CompleteStructMember member_pose_covariance = TypeObjectUtils::build_complete_struct_member(common_pose_covariance, detail_pose_covariance);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_pose_covariance);
        }
        {
            TypeIdentifierPair type_ids_linear_x;
            ReturnCode_t return_code_linear_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_linear_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_linear_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_linear_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "linear_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_linear_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_linear_x = 0x0000000b;
            bool common_linear_x_ec {false};
            CommonStructMember common_linear_x {TypeObjectUtils::build_common_struct_member(member_id_linear_x, member_flags_linear_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_linear_x, common_linear_x_ec))};
            if (!common_linear_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure linear_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_linear_x = "linear_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_linear_x;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_linear_x = TypeObjectUtils::build_complete_member_detail(name_linear_x, member_ann_builtin_linear_x, ann_custom_OdomData);
            CompleteStructMember member_linear_x = TypeObjectUtils::build_complete_struct_member(common_linear_x, detail_linear_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_linear_x);
        }
        {
            TypeIdentifierPair type_ids_linear_y;
            ReturnCode_t return_code_linear_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_linear_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_linear_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_linear_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "linear_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_linear_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_linear_y = 0x0000000c;
            bool common_linear_y_ec {false};
            CommonStructMember common_linear_y {TypeObjectUtils::build_common_struct_member(member_id_linear_y, member_flags_linear_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_linear_y, common_linear_y_ec))};
            if (!common_linear_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure linear_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_linear_y = "linear_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_linear_y;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_linear_y = TypeObjectUtils::build_complete_member_detail(name_linear_y, member_ann_builtin_linear_y, ann_custom_OdomData);
            CompleteStructMember member_linear_y = TypeObjectUtils::build_complete_struct_member(common_linear_y, detail_linear_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_linear_y);
        }
        {
            TypeIdentifierPair type_ids_linear_z;
            ReturnCode_t return_code_linear_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_linear_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_linear_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_linear_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "linear_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_linear_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_linear_z = 0x0000000d;
            bool common_linear_z_ec {false};
            CommonStructMember common_linear_z {TypeObjectUtils::build_common_struct_member(member_id_linear_z, member_flags_linear_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_linear_z, common_linear_z_ec))};
            if (!common_linear_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure linear_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_linear_z = "linear_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_linear_z;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_linear_z = TypeObjectUtils::build_complete_member_detail(name_linear_z, member_ann_builtin_linear_z, ann_custom_OdomData);
            CompleteStructMember member_linear_z = TypeObjectUtils::build_complete_struct_member(common_linear_z, detail_linear_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_linear_z);
        }
        {
            TypeIdentifierPair type_ids_angular_x;
            ReturnCode_t return_code_angular_x {eprosima::fastdds::dds::RETCODE_OK};
            return_code_angular_x =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_angular_x);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_angular_x)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "angular_x Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_angular_x = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_angular_x = 0x0000000e;
            bool common_angular_x_ec {false};
            CommonStructMember common_angular_x {TypeObjectUtils::build_common_struct_member(member_id_angular_x, member_flags_angular_x, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_angular_x, common_angular_x_ec))};
            if (!common_angular_x_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure angular_x member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_angular_x = "angular_x";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_angular_x;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_angular_x = TypeObjectUtils::build_complete_member_detail(name_angular_x, member_ann_builtin_angular_x, ann_custom_OdomData);
            CompleteStructMember member_angular_x = TypeObjectUtils::build_complete_struct_member(common_angular_x, detail_angular_x);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_angular_x);
        }
        {
            TypeIdentifierPair type_ids_angular_y;
            ReturnCode_t return_code_angular_y {eprosima::fastdds::dds::RETCODE_OK};
            return_code_angular_y =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_angular_y);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_angular_y)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "angular_y Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_angular_y = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_angular_y = 0x0000000f;
            bool common_angular_y_ec {false};
            CommonStructMember common_angular_y {TypeObjectUtils::build_common_struct_member(member_id_angular_y, member_flags_angular_y, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_angular_y, common_angular_y_ec))};
            if (!common_angular_y_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure angular_y member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_angular_y = "angular_y";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_angular_y;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_angular_y = TypeObjectUtils::build_complete_member_detail(name_angular_y, member_ann_builtin_angular_y, ann_custom_OdomData);
            CompleteStructMember member_angular_y = TypeObjectUtils::build_complete_struct_member(common_angular_y, detail_angular_y);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_angular_y);
        }
        {
            TypeIdentifierPair type_ids_angular_z;
            ReturnCode_t return_code_angular_z {eprosima::fastdds::dds::RETCODE_OK};
            return_code_angular_z =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_double", type_ids_angular_z);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_angular_z)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "angular_z Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_angular_z = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_angular_z = 0x00000010;
            bool common_angular_z_ec {false};
            CommonStructMember common_angular_z {TypeObjectUtils::build_common_struct_member(member_id_angular_z, member_flags_angular_z, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_angular_z, common_angular_z_ec))};
            if (!common_angular_z_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure angular_z member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_angular_z = "angular_z";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_angular_z;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_angular_z = TypeObjectUtils::build_complete_member_detail(name_angular_z, member_ann_builtin_angular_z, ann_custom_OdomData);
            CompleteStructMember member_angular_z = TypeObjectUtils::build_complete_struct_member(common_angular_z, detail_angular_z);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_angular_z);
        }
        {
            TypeIdentifierPair type_ids_twist_covariance;
            ReturnCode_t return_code_twist_covariance {eprosima::fastdds::dds::RETCODE_OK};
            return_code_twist_covariance =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_sequence_double_36", type_ids_twist_covariance);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_twist_covariance)
            {
                return_code_twist_covariance =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_double", type_ids_twist_covariance);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_twist_covariance)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Sequence element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_sequence_double_36_ec {false};
                TypeIdentifier* element_identifier_anonymous_sequence_double_36 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_twist_covariance, element_identifier_anonymous_sequence_double_36_ec))};
                if (!element_identifier_anonymous_sequence_double_36_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Sequence element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_sequence_double_36 = EK_COMPLETE;
                if (TK_NONE == type_ids_twist_covariance.type_identifier2()._d())
                {
                    equiv_kind_anonymous_sequence_double_36 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_sequence_double_36 = 0;
                PlainCollectionHeader header_anonymous_sequence_double_36 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_sequence_double_36, element_flags_anonymous_sequence_double_36);
                {
                    SBound bound = static_cast<SBound>(36);
                    PlainSequenceSElemDefn seq_sdefn = TypeObjectUtils::build_plain_sequence_s_elem_defn(header_anonymous_sequence_double_36, bound,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_sequence_double_36));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_sequence_type_identifier(seq_sdefn, "anonymous_sequence_double_36", type_ids_twist_covariance))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_sequence_double_36 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_twist_covariance = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_twist_covariance = 0x00000011;
            bool common_twist_covariance_ec {false};
            CommonStructMember common_twist_covariance {TypeObjectUtils::build_common_struct_member(member_id_twist_covariance, member_flags_twist_covariance, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_twist_covariance, common_twist_covariance_ec))};
            if (!common_twist_covariance_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure twist_covariance member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_twist_covariance = "twist_covariance";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_twist_covariance;
            ann_custom_OdomData.reset();
            CompleteMemberDetail detail_twist_covariance = TypeObjectUtils::build_complete_member_detail(name_twist_covariance, member_ann_builtin_twist_covariance, ann_custom_OdomData);
            CompleteStructMember member_twist_covariance = TypeObjectUtils::build_complete_struct_member(common_twist_covariance, detail_twist_covariance);
            TypeObjectUtils::add_complete_struct_member(member_seq_OdomData, member_twist_covariance);
        }
        CompleteStructType struct_type_OdomData = TypeObjectUtils::build_complete_struct_type(struct_flags_OdomData, header_OdomData, member_seq_OdomData);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_OdomData, type_name_OdomData.to_string(), type_ids_OdomData))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "odom_topic_base::OdomData already registered in TypeObjectRegistry for a different type.");
        }
    }
}
} // namespace odom_topic_base

