// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file odom_topic_base.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.3.0).
 */

#ifndef FAST_DDS_GENERATED__ODOM_TOPIC_BASE_ODOM_TOPIC_BASE_HPP
#define FAST_DDS_GENERATED__ODOM_TOPIC_BASE_ODOM_TOPIC_BASE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(ODOM_TOPIC_BASE_SOURCE)
#define ODOM_TOPIC_BASE_DllAPI __declspec( dllexport )
#else
#define ODOM_TOPIC_BASE_DllAPI __declspec( dllimport )
#endif // ODOM_TOPIC_BASE_SOURCE
#else
#define ODOM_TOPIC_BASE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define ODOM_TOPIC_BASE_DllAPI
#endif // _WIN32

namespace odom_topic_base {

const uint32_t MAX_FRAME_ID_LEN = 128;
const uint32_t COVARIANCE_SIZE = 36;
/*!
 * @brief This class represents the structure OdomData defined by the user in the IDL file.
 * @ingroup odom_topic_base
 */
class OdomData
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport OdomData()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~OdomData()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object OdomData that will be copied.
     */
    eProsima_user_DllExport OdomData(
            const OdomData& x)
    {
                    m_frame_id = x.m_frame_id;

                    m_child_frame_id = x.m_child_frame_id;

                    m_timestamp = x.m_timestamp;

                    m_position_x = x.m_position_x;

                    m_position_y = x.m_position_y;

                    m_position_z = x.m_position_z;

                    m_orientation_x = x.m_orientation_x;

                    m_orientation_y = x.m_orientation_y;

                    m_orientation_z = x.m_orientation_z;

                    m_orientation_w = x.m_orientation_w;

                    m_pose_covariance = x.m_pose_covariance;

                    m_linear_x = x.m_linear_x;

                    m_linear_y = x.m_linear_y;

                    m_linear_z = x.m_linear_z;

                    m_angular_x = x.m_angular_x;

                    m_angular_y = x.m_angular_y;

                    m_angular_z = x.m_angular_z;

                    m_twist_covariance = x.m_twist_covariance;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object OdomData that will be copied.
     */
    eProsima_user_DllExport OdomData(
            OdomData&& x) noexcept
    {
        m_frame_id = std::move(x.m_frame_id);
        m_child_frame_id = std::move(x.m_child_frame_id);
        m_timestamp = x.m_timestamp;
        m_position_x = x.m_position_x;
        m_position_y = x.m_position_y;
        m_position_z = x.m_position_z;
        m_orientation_x = x.m_orientation_x;
        m_orientation_y = x.m_orientation_y;
        m_orientation_z = x.m_orientation_z;
        m_orientation_w = x.m_orientation_w;
        m_pose_covariance = std::move(x.m_pose_covariance);
        m_linear_x = x.m_linear_x;
        m_linear_y = x.m_linear_y;
        m_linear_z = x.m_linear_z;
        m_angular_x = x.m_angular_x;
        m_angular_y = x.m_angular_y;
        m_angular_z = x.m_angular_z;
        m_twist_covariance = std::move(x.m_twist_covariance);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object OdomData that will be copied.
     */
    eProsima_user_DllExport OdomData& operator =(
            const OdomData& x)
    {

                    m_frame_id = x.m_frame_id;

                    m_child_frame_id = x.m_child_frame_id;

                    m_timestamp = x.m_timestamp;

                    m_position_x = x.m_position_x;

                    m_position_y = x.m_position_y;

                    m_position_z = x.m_position_z;

                    m_orientation_x = x.m_orientation_x;

                    m_orientation_y = x.m_orientation_y;

                    m_orientation_z = x.m_orientation_z;

                    m_orientation_w = x.m_orientation_w;

                    m_pose_covariance = x.m_pose_covariance;

                    m_linear_x = x.m_linear_x;

                    m_linear_y = x.m_linear_y;

                    m_linear_z = x.m_linear_z;

                    m_angular_x = x.m_angular_x;

                    m_angular_y = x.m_angular_y;

                    m_angular_z = x.m_angular_z;

                    m_twist_covariance = x.m_twist_covariance;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object OdomData that will be copied.
     */
    eProsima_user_DllExport OdomData& operator =(
            OdomData&& x) noexcept
    {

        m_frame_id = std::move(x.m_frame_id);
        m_child_frame_id = std::move(x.m_child_frame_id);
        m_timestamp = x.m_timestamp;
        m_position_x = x.m_position_x;
        m_position_y = x.m_position_y;
        m_position_z = x.m_position_z;
        m_orientation_x = x.m_orientation_x;
        m_orientation_y = x.m_orientation_y;
        m_orientation_z = x.m_orientation_z;
        m_orientation_w = x.m_orientation_w;
        m_pose_covariance = std::move(x.m_pose_covariance);
        m_linear_x = x.m_linear_x;
        m_linear_y = x.m_linear_y;
        m_linear_z = x.m_linear_z;
        m_angular_x = x.m_angular_x;
        m_angular_y = x.m_angular_y;
        m_angular_z = x.m_angular_z;
        m_twist_covariance = std::move(x.m_twist_covariance);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x OdomData object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const OdomData& x) const
    {
        return (m_frame_id == x.m_frame_id &&
           m_child_frame_id == x.m_child_frame_id &&
           m_timestamp == x.m_timestamp &&
           m_position_x == x.m_position_x &&
           m_position_y == x.m_position_y &&
           m_position_z == x.m_position_z &&
           m_orientation_x == x.m_orientation_x &&
           m_orientation_y == x.m_orientation_y &&
           m_orientation_z == x.m_orientation_z &&
           m_orientation_w == x.m_orientation_w &&
           m_pose_covariance == x.m_pose_covariance &&
           m_linear_x == x.m_linear_x &&
           m_linear_y == x.m_linear_y &&
           m_linear_z == x.m_linear_z &&
           m_angular_x == x.m_angular_x &&
           m_angular_y == x.m_angular_y &&
           m_angular_z == x.m_angular_z &&
           m_twist_covariance == x.m_twist_covariance);
    }

    /*!
     * @brief Comparison operator.
     * @param x OdomData object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const OdomData& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member frame_id
     * @param _frame_id New value to be copied in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& _frame_id)
    {
        m_frame_id = _frame_id;
    }

    /*!
     * @brief This function moves the value in member frame_id
     * @param _frame_id New value to be moved in member frame_id
     */
    eProsima_user_DllExport void frame_id(
            eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>&& _frame_id)
    {
        m_frame_id = std::move(_frame_id);
    }

    /*!
     * @brief This function returns a constant reference to member frame_id
     * @return Constant reference to member frame_id
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& frame_id() const
    {
        return m_frame_id;
    }

    /*!
     * @brief This function returns a reference to member frame_id
     * @return Reference to member frame_id
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& frame_id()
    {
        return m_frame_id;
    }


    /*!
     * @brief This function copies the value in member child_frame_id
     * @param _child_frame_id New value to be copied in member child_frame_id
     */
    eProsima_user_DllExport void child_frame_id(
            const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& _child_frame_id)
    {
        m_child_frame_id = _child_frame_id;
    }

    /*!
     * @brief This function moves the value in member child_frame_id
     * @param _child_frame_id New value to be moved in member child_frame_id
     */
    eProsima_user_DllExport void child_frame_id(
            eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>&& _child_frame_id)
    {
        m_child_frame_id = std::move(_child_frame_id);
    }

    /*!
     * @brief This function returns a constant reference to member child_frame_id
     * @return Constant reference to member child_frame_id
     */
    eProsima_user_DllExport const eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& child_frame_id() const
    {
        return m_child_frame_id;
    }

    /*!
     * @brief This function returns a reference to member child_frame_id
     * @return Reference to member child_frame_id
     */
    eProsima_user_DllExport eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN>& child_frame_id()
    {
        return m_child_frame_id;
    }


    /*!
     * @brief This function sets a value in member timestamp
     * @param _timestamp New value for member timestamp
     */
    eProsima_user_DllExport void timestamp(
            uint64_t _timestamp)
    {
        m_timestamp = _timestamp;
    }

    /*!
     * @brief This function returns the value of member timestamp
     * @return Value of member timestamp
     */
    eProsima_user_DllExport uint64_t timestamp() const
    {
        return m_timestamp;
    }

    /*!
     * @brief This function returns a reference to member timestamp
     * @return Reference to member timestamp
     */
    eProsima_user_DllExport uint64_t& timestamp()
    {
        return m_timestamp;
    }


    /*!
     * @brief This function sets a value in member position_x
     * @param _position_x New value for member position_x
     */
    eProsima_user_DllExport void position_x(
            double _position_x)
    {
        m_position_x = _position_x;
    }

    /*!
     * @brief This function returns the value of member position_x
     * @return Value of member position_x
     */
    eProsima_user_DllExport double position_x() const
    {
        return m_position_x;
    }

    /*!
     * @brief This function returns a reference to member position_x
     * @return Reference to member position_x
     */
    eProsima_user_DllExport double& position_x()
    {
        return m_position_x;
    }


    /*!
     * @brief This function sets a value in member position_y
     * @param _position_y New value for member position_y
     */
    eProsima_user_DllExport void position_y(
            double _position_y)
    {
        m_position_y = _position_y;
    }

    /*!
     * @brief This function returns the value of member position_y
     * @return Value of member position_y
     */
    eProsima_user_DllExport double position_y() const
    {
        return m_position_y;
    }

    /*!
     * @brief This function returns a reference to member position_y
     * @return Reference to member position_y
     */
    eProsima_user_DllExport double& position_y()
    {
        return m_position_y;
    }


    /*!
     * @brief This function sets a value in member position_z
     * @param _position_z New value for member position_z
     */
    eProsima_user_DllExport void position_z(
            double _position_z)
    {
        m_position_z = _position_z;
    }

    /*!
     * @brief This function returns the value of member position_z
     * @return Value of member position_z
     */
    eProsima_user_DllExport double position_z() const
    {
        return m_position_z;
    }

    /*!
     * @brief This function returns a reference to member position_z
     * @return Reference to member position_z
     */
    eProsima_user_DllExport double& position_z()
    {
        return m_position_z;
    }


    /*!
     * @brief This function sets a value in member orientation_x
     * @param _orientation_x New value for member orientation_x
     */
    eProsima_user_DllExport void orientation_x(
            double _orientation_x)
    {
        m_orientation_x = _orientation_x;
    }

    /*!
     * @brief This function returns the value of member orientation_x
     * @return Value of member orientation_x
     */
    eProsima_user_DllExport double orientation_x() const
    {
        return m_orientation_x;
    }

    /*!
     * @brief This function returns a reference to member orientation_x
     * @return Reference to member orientation_x
     */
    eProsima_user_DllExport double& orientation_x()
    {
        return m_orientation_x;
    }


    /*!
     * @brief This function sets a value in member orientation_y
     * @param _orientation_y New value for member orientation_y
     */
    eProsima_user_DllExport void orientation_y(
            double _orientation_y)
    {
        m_orientation_y = _orientation_y;
    }

    /*!
     * @brief This function returns the value of member orientation_y
     * @return Value of member orientation_y
     */
    eProsima_user_DllExport double orientation_y() const
    {
        return m_orientation_y;
    }

    /*!
     * @brief This function returns a reference to member orientation_y
     * @return Reference to member orientation_y
     */
    eProsima_user_DllExport double& orientation_y()
    {
        return m_orientation_y;
    }


    /*!
     * @brief This function sets a value in member orientation_z
     * @param _orientation_z New value for member orientation_z
     */
    eProsima_user_DllExport void orientation_z(
            double _orientation_z)
    {
        m_orientation_z = _orientation_z;
    }

    /*!
     * @brief This function returns the value of member orientation_z
     * @return Value of member orientation_z
     */
    eProsima_user_DllExport double orientation_z() const
    {
        return m_orientation_z;
    }

    /*!
     * @brief This function returns a reference to member orientation_z
     * @return Reference to member orientation_z
     */
    eProsima_user_DllExport double& orientation_z()
    {
        return m_orientation_z;
    }


    /*!
     * @brief This function sets a value in member orientation_w
     * @param _orientation_w New value for member orientation_w
     */
    eProsima_user_DllExport void orientation_w(
            double _orientation_w)
    {
        m_orientation_w = _orientation_w;
    }

    /*!
     * @brief This function returns the value of member orientation_w
     * @return Value of member orientation_w
     */
    eProsima_user_DllExport double orientation_w() const
    {
        return m_orientation_w;
    }

    /*!
     * @brief This function returns a reference to member orientation_w
     * @return Reference to member orientation_w
     */
    eProsima_user_DllExport double& orientation_w()
    {
        return m_orientation_w;
    }


    /*!
     * @brief This function copies the value in member pose_covariance
     * @param _pose_covariance New value to be copied in member pose_covariance
     */
    eProsima_user_DllExport void pose_covariance(
            const std::vector<double>& _pose_covariance)
    {
        m_pose_covariance = _pose_covariance;
    }

    /*!
     * @brief This function moves the value in member pose_covariance
     * @param _pose_covariance New value to be moved in member pose_covariance
     */
    eProsima_user_DllExport void pose_covariance(
            std::vector<double>&& _pose_covariance)
    {
        m_pose_covariance = std::move(_pose_covariance);
    }

    /*!
     * @brief This function returns a constant reference to member pose_covariance
     * @return Constant reference to member pose_covariance
     */
    eProsima_user_DllExport const std::vector<double>& pose_covariance() const
    {
        return m_pose_covariance;
    }

    /*!
     * @brief This function returns a reference to member pose_covariance
     * @return Reference to member pose_covariance
     */
    eProsima_user_DllExport std::vector<double>& pose_covariance()
    {
        return m_pose_covariance;
    }


    /*!
     * @brief This function sets a value in member linear_x
     * @param _linear_x New value for member linear_x
     */
    eProsima_user_DllExport void linear_x(
            double _linear_x)
    {
        m_linear_x = _linear_x;
    }

    /*!
     * @brief This function returns the value of member linear_x
     * @return Value of member linear_x
     */
    eProsima_user_DllExport double linear_x() const
    {
        return m_linear_x;
    }

    /*!
     * @brief This function returns a reference to member linear_x
     * @return Reference to member linear_x
     */
    eProsima_user_DllExport double& linear_x()
    {
        return m_linear_x;
    }


    /*!
     * @brief This function sets a value in member linear_y
     * @param _linear_y New value for member linear_y
     */
    eProsima_user_DllExport void linear_y(
            double _linear_y)
    {
        m_linear_y = _linear_y;
    }

    /*!
     * @brief This function returns the value of member linear_y
     * @return Value of member linear_y
     */
    eProsima_user_DllExport double linear_y() const
    {
        return m_linear_y;
    }

    /*!
     * @brief This function returns a reference to member linear_y
     * @return Reference to member linear_y
     */
    eProsima_user_DllExport double& linear_y()
    {
        return m_linear_y;
    }


    /*!
     * @brief This function sets a value in member linear_z
     * @param _linear_z New value for member linear_z
     */
    eProsima_user_DllExport void linear_z(
            double _linear_z)
    {
        m_linear_z = _linear_z;
    }

    /*!
     * @brief This function returns the value of member linear_z
     * @return Value of member linear_z
     */
    eProsima_user_DllExport double linear_z() const
    {
        return m_linear_z;
    }

    /*!
     * @brief This function returns a reference to member linear_z
     * @return Reference to member linear_z
     */
    eProsima_user_DllExport double& linear_z()
    {
        return m_linear_z;
    }


    /*!
     * @brief This function sets a value in member angular_x
     * @param _angular_x New value for member angular_x
     */
    eProsima_user_DllExport void angular_x(
            double _angular_x)
    {
        m_angular_x = _angular_x;
    }

    /*!
     * @brief This function returns the value of member angular_x
     * @return Value of member angular_x
     */
    eProsima_user_DllExport double angular_x() const
    {
        return m_angular_x;
    }

    /*!
     * @brief This function returns a reference to member angular_x
     * @return Reference to member angular_x
     */
    eProsima_user_DllExport double& angular_x()
    {
        return m_angular_x;
    }


    /*!
     * @brief This function sets a value in member angular_y
     * @param _angular_y New value for member angular_y
     */
    eProsima_user_DllExport void angular_y(
            double _angular_y)
    {
        m_angular_y = _angular_y;
    }

    /*!
     * @brief This function returns the value of member angular_y
     * @return Value of member angular_y
     */
    eProsima_user_DllExport double angular_y() const
    {
        return m_angular_y;
    }

    /*!
     * @brief This function returns a reference to member angular_y
     * @return Reference to member angular_y
     */
    eProsima_user_DllExport double& angular_y()
    {
        return m_angular_y;
    }


    /*!
     * @brief This function sets a value in member angular_z
     * @param _angular_z New value for member angular_z
     */
    eProsima_user_DllExport void angular_z(
            double _angular_z)
    {
        m_angular_z = _angular_z;
    }

    /*!
     * @brief This function returns the value of member angular_z
     * @return Value of member angular_z
     */
    eProsima_user_DllExport double angular_z() const
    {
        return m_angular_z;
    }

    /*!
     * @brief This function returns a reference to member angular_z
     * @return Reference to member angular_z
     */
    eProsima_user_DllExport double& angular_z()
    {
        return m_angular_z;
    }


    /*!
     * @brief This function copies the value in member twist_covariance
     * @param _twist_covariance New value to be copied in member twist_covariance
     */
    eProsima_user_DllExport void twist_covariance(
            const std::vector<double>& _twist_covariance)
    {
        m_twist_covariance = _twist_covariance;
    }

    /*!
     * @brief This function moves the value in member twist_covariance
     * @param _twist_covariance New value to be moved in member twist_covariance
     */
    eProsima_user_DllExport void twist_covariance(
            std::vector<double>&& _twist_covariance)
    {
        m_twist_covariance = std::move(_twist_covariance);
    }

    /*!
     * @brief This function returns a constant reference to member twist_covariance
     * @return Constant reference to member twist_covariance
     */
    eProsima_user_DllExport const std::vector<double>& twist_covariance() const
    {
        return m_twist_covariance;
    }

    /*!
     * @brief This function returns a reference to member twist_covariance
     * @return Reference to member twist_covariance
     */
    eProsima_user_DllExport std::vector<double>& twist_covariance()
    {
        return m_twist_covariance;
    }



private:

    eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN> m_frame_id;
    eprosima::fastcdr::fixed_string<MAX_FRAME_ID_LEN> m_child_frame_id;
    uint64_t m_timestamp{0};
    double m_position_x{0.0};
    double m_position_y{0.0};
    double m_position_z{0.0};
    double m_orientation_x{0.0};
    double m_orientation_y{0.0};
    double m_orientation_z{0.0};
    double m_orientation_w{0.0};
    std::vector<double> m_pose_covariance;
    double m_linear_x{0.0};
    double m_linear_y{0.0};
    double m_linear_z{0.0};
    double m_angular_x{0.0};
    double m_angular_y{0.0};
    double m_angular_z{0.0};
    std::vector<double> m_twist_covariance;

};

} // namespace odom_topic_base

#endif // _FAST_DDS_GENERATED_ODOM_TOPIC_BASE_ODOM_TOPIC_BASE_HPP_


