// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file motor_command_16Application.cxx
 * This file contains the implementation of the application functions.
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "motor_command_16Application.hpp"

#include "motor_command_16PublisherApp.hpp"
#include "motor_command_16SubscriberApp.hpp"

//! Factory method to create a publisher or subscriber
std::shared_ptr<motor_command_16Application> motor_command_16Application::make_app(
        const int& domain_id,
        const std::string& entity_kind)
{
    std::shared_ptr<motor_command_16Application> entity;
    if (strcmp(entity_kind.c_str(), "publisher") == 0)
    {
        entity = std::make_shared<motor_command_16PublisherApp>(domain_id);
    }
    else if (strcmp(entity_kind.c_str(), "subscriber") == 0)
    {
        entity = std::make_shared<motor_command_16SubscriberApp>(domain_id);
    }
    else
    {
        throw std::runtime_error("Entity initialization failed");
    }
    return entity;
}