// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file motor_command_16TypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.1.0).
 */

#include "motor_command_16TypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>

#include "motor_command_16.hpp"


using namespace eprosima::fastdds::dds::xtypes;

namespace Motor_Command_16 {
// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_motor_cmd_type_identifier(
        TypeIdentifierPair& type_ids_motor_cmd)
{

    ReturnCode_t return_code_motor_cmd {eprosima::fastdds::dds::RETCODE_OK};
    return_code_motor_cmd =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "Motor_Command_16::motor_cmd", type_ids_motor_cmd);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_motor_cmd)
    {
        StructTypeFlag struct_flags_motor_cmd = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::FINAL,
                false, false);
        QualifiedTypeName type_name_motor_cmd = "Motor_Command_16::motor_cmd";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_motor_cmd;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_motor_cmd;
        AppliedAnnotationSeq tmp_ann_custom_motor_cmd;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_motor_cmd;
        if (!tmp_ann_custom_motor_cmd.empty())
        {
            ann_custom_motor_cmd = tmp_ann_custom_motor_cmd;
        }

        CompleteTypeDetail detail_motor_cmd = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_motor_cmd, ann_custom_motor_cmd, type_name_motor_cmd.to_string());
        CompleteStructHeader header_motor_cmd;
        header_motor_cmd = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_motor_cmd);
        CompleteStructMemberSeq member_seq_motor_cmd;
        {
            TypeIdentifierPair type_ids_kp;
            ReturnCode_t return_code_kp {eprosima::fastdds::dds::RETCODE_OK};
            return_code_kp =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_kp);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_kp)
            {
                return_code_kp =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_kp);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_kp)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kp, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_kp.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_kp))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_kp = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_kp = 0x00000000;
            bool common_kp_ec {false};
            CommonStructMember common_kp {TypeObjectUtils::build_common_struct_member(member_id_kp, member_flags_kp, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kp, common_kp_ec))};
            if (!common_kp_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure kp member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_kp = "kp";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_kp;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_kp = TypeObjectUtils::build_complete_member_detail(name_kp, member_ann_builtin_kp, ann_custom_motor_cmd);
            CompleteStructMember member_kp = TypeObjectUtils::build_complete_struct_member(common_kp, detail_kp);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_kp);
        }
        {
            TypeIdentifierPair type_ids_kd;
            ReturnCode_t return_code_kd {eprosima::fastdds::dds::RETCODE_OK};
            return_code_kd =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_kd);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_kd)
            {
                return_code_kd =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_kd);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_kd)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kd, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_kd.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_kd))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_kd = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_kd = 0x00000001;
            bool common_kd_ec {false};
            CommonStructMember common_kd {TypeObjectUtils::build_common_struct_member(member_id_kd, member_flags_kd, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_kd, common_kd_ec))};
            if (!common_kd_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure kd member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_kd = "kd";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_kd;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_kd = TypeObjectUtils::build_complete_member_detail(name_kd, member_ann_builtin_kd, ann_custom_motor_cmd);
            CompleteStructMember member_kd = TypeObjectUtils::build_complete_struct_member(common_kd, detail_kd);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_kd);
        }
        {
            TypeIdentifierPair type_ids_pos;
            ReturnCode_t return_code_pos {eprosima::fastdds::dds::RETCODE_OK};
            return_code_pos =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_pos);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_pos)
            {
                return_code_pos =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_pos);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_pos)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pos, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_pos.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_pos))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_pos = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_pos = 0x00000002;
            bool common_pos_ec {false};
            CommonStructMember common_pos {TypeObjectUtils::build_common_struct_member(member_id_pos, member_flags_pos, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_pos, common_pos_ec))};
            if (!common_pos_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure pos member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_pos = "pos";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_pos;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_pos = TypeObjectUtils::build_complete_member_detail(name_pos, member_ann_builtin_pos, ann_custom_motor_cmd);
            CompleteStructMember member_pos = TypeObjectUtils::build_complete_struct_member(common_pos, detail_pos);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_pos);
        }
        {
            TypeIdentifierPair type_ids_vel;
            ReturnCode_t return_code_vel {eprosima::fastdds::dds::RETCODE_OK};
            return_code_vel =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_vel);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_vel)
            {
                return_code_vel =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_vel);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_vel)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vel, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_vel.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_vel))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_vel = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_vel = 0x00000003;
            bool common_vel_ec {false};
            CommonStructMember common_vel {TypeObjectUtils::build_common_struct_member(member_id_vel, member_flags_vel, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_vel, common_vel_ec))};
            if (!common_vel_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure vel member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_vel = "vel";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_vel;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_vel = TypeObjectUtils::build_complete_member_detail(name_vel, member_ann_builtin_vel, ann_custom_motor_cmd);
            CompleteStructMember member_vel = TypeObjectUtils::build_complete_struct_member(common_vel, detail_vel);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_vel);
        }
        {
            TypeIdentifierPair type_ids_torque;
            ReturnCode_t return_code_torque {eprosima::fastdds::dds::RETCODE_OK};
            return_code_torque =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_torque);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque)
            {
                return_code_torque =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_torque);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_torque)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_torque.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_torque))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_torque = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_torque = 0x00000004;
            bool common_torque_ec {false};
            CommonStructMember common_torque {TypeObjectUtils::build_common_struct_member(member_id_torque, member_flags_torque, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_torque, common_torque_ec))};
            if (!common_torque_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure torque member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_torque = "torque";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_torque;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_torque = TypeObjectUtils::build_complete_member_detail(name_torque, member_ann_builtin_torque, ann_custom_motor_cmd);
            CompleteStructMember member_torque = TypeObjectUtils::build_complete_struct_member(common_torque, detail_torque);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_torque);
        }
        {
            TypeIdentifierPair type_ids_ff_torque;
            ReturnCode_t return_code_ff_torque {eprosima::fastdds::dds::RETCODE_OK};
            return_code_ff_torque =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_float_16", type_ids_ff_torque);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_ff_torque)
            {
                return_code_ff_torque =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_float", type_ids_ff_torque);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_ff_torque)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_float_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_float_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ff_torque, element_identifier_anonymous_array_float_16_ec))};
                if (!element_identifier_anonymous_array_float_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_float_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_ff_torque.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_float_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_float_16 = 0;
                PlainCollectionHeader header_anonymous_array_float_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_float_16, element_flags_anonymous_array_float_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_float_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_float_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_float_16", type_ids_ff_torque))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_float_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_ff_torque = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_ff_torque = 0x00000005;
            bool common_ff_torque_ec {false};
            CommonStructMember common_ff_torque {TypeObjectUtils::build_common_struct_member(member_id_ff_torque, member_flags_ff_torque, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_ff_torque, common_ff_torque_ec))};
            if (!common_ff_torque_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure ff_torque member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_ff_torque = "ff_torque";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_ff_torque;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_ff_torque = TypeObjectUtils::build_complete_member_detail(name_ff_torque, member_ann_builtin_ff_torque, ann_custom_motor_cmd);
            CompleteStructMember member_ff_torque = TypeObjectUtils::build_complete_struct_member(common_ff_torque, detail_ff_torque);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_ff_torque);
        }
        {
            TypeIdentifierPair type_ids_mode;
            ReturnCode_t return_code_mode {eprosima::fastdds::dds::RETCODE_OK};
            return_code_mode =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_array_uint32_t_16", type_ids_mode);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_mode)
            {
                return_code_mode =
                    eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                    "_uint32_t", type_ids_mode);

                if (eprosima::fastdds::dds::RETCODE_OK != return_code_mode)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "Array element TypeIdentifier unknown to TypeObjectRegistry.");
                    return;
                }
                bool element_identifier_anonymous_array_uint32_t_16_ec {false};
                TypeIdentifier* element_identifier_anonymous_array_uint32_t_16 {new TypeIdentifier(TypeObjectUtils::retrieve_complete_type_identifier(type_ids_mode, element_identifier_anonymous_array_uint32_t_16_ec))};
                if (!element_identifier_anonymous_array_uint32_t_16_ec)
                {
                    EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Array element TypeIdentifier inconsistent.");
                    return;
                }
                EquivalenceKind equiv_kind_anonymous_array_uint32_t_16 = EK_COMPLETE;
                if (TK_NONE == type_ids_mode.type_identifier2()._d())
                {
                    equiv_kind_anonymous_array_uint32_t_16 = EK_BOTH;
                }
                CollectionElementFlag element_flags_anonymous_array_uint32_t_16 = 0;
                PlainCollectionHeader header_anonymous_array_uint32_t_16 = TypeObjectUtils::build_plain_collection_header(equiv_kind_anonymous_array_uint32_t_16, element_flags_anonymous_array_uint32_t_16);
                {
                    SBoundSeq array_bound_seq;
                        TypeObjectUtils::add_array_dimension(array_bound_seq, static_cast<SBound>(16));

                    PlainArraySElemDefn array_sdefn = TypeObjectUtils::build_plain_array_s_elem_defn(header_anonymous_array_uint32_t_16, array_bound_seq,
                                eprosima::fastcdr::external<TypeIdentifier>(element_identifier_anonymous_array_uint32_t_16));
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_array_type_identifier(array_sdefn, "anonymous_array_uint32_t_16", type_ids_mode))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_array_uint32_t_16 already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_mode = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_mode = 0x00000006;
            bool common_mode_ec {false};
            CommonStructMember common_mode {TypeObjectUtils::build_common_struct_member(member_id_mode, member_flags_mode, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_mode, common_mode_ec))};
            if (!common_mode_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure mode member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_mode = "mode";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_mode;
            ann_custom_motor_cmd.reset();
            CompleteMemberDetail detail_mode = TypeObjectUtils::build_complete_member_detail(name_mode, member_ann_builtin_mode, ann_custom_motor_cmd);
            CompleteStructMember member_mode = TypeObjectUtils::build_complete_struct_member(common_mode, detail_mode);
            TypeObjectUtils::add_complete_struct_member(member_seq_motor_cmd, member_mode);
        }
        CompleteStructType struct_type_motor_cmd = TypeObjectUtils::build_complete_struct_type(struct_flags_motor_cmd, header_motor_cmd, member_seq_motor_cmd);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_motor_cmd, type_name_motor_cmd.to_string(), type_ids_motor_cmd))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "Motor_Command_16::motor_cmd already registered in TypeObjectRegistry for a different type.");
        }
    }
}

} // namespace Motor_Command_16

